### ISSUE TITLE
unique value filtering for impact

### ISSUE THREAD

**Issue by julienthevenon** [labsquare/cutevariant#100]
apply filter for multiple occurences of identical terms in one filter. 
Ex : 
Impact column has tags : HIGH, MODERATE, MODIFIER, LOW.
Several rows have LOW; LOW,LOW; LOW,LOW,LOW ... etc until >10 occurrences. Filtering at once such pattern would be great

**Comment by dridk** [comment]
Looks like a bug with VEP parser. I m investigating
