### ISSUE TITLE
Compute mendelian status

### ISSUE THREAD

**Issue by julienthevenon** [labsquare/cutevariant#101]
Computing mendelian inheritance from trio genotype, 

- [x]  denovo
parent1.GT="0/0" & parent2.GT="0/0" & index.GT="0/1"
**beware of phased variants with | separators**

- [ ]  bilallelic
parent1.GT="0/1" & parent2.GT="0/1" & index.GT="1/1"
GeneX : varY (parent1.GT="0/1" & parent2.GT="0/0" & index.GT="0/1") &  varZ (parent1.GT="0/0" & parent2.GT="0/1" & index.GT="0/1")
**beware with multiallelic variants, ambigous genotypings (both parents heterozygous for multiple variants)**
*stratify the impact depending on variant impact (HIGH/HIGH; HIGH/MODERATE; MODERATE/MODERATE; HIGH/MODIFIER; HIGH/LOW; MODERATE/MODIFIER; MODERATE/LOW; MODIFIER/MODIFIER; MODIFIER/LOW; LOW/LOW)*

**Comment by dridk** [comment]
todo: 
- Use a ped file to defined the trio 
- What about analysis with more than 3 patients ?

**Comment by julienthevenon** [comment]
using a PED format file allow the contruction of complex family trees (inferring, if necessary, individuals that may not be analysed)

**Comment by dridk** [comment]
Retro engineer this : 
https://github.com/moonso/genmod 

We should compute this score since we have now pedigree features.

**Comment by dridk** [comment]
Acutally, those filters can be done with special fields. Even with more than 3 samples;
See documentation here : https://github.com/labsquare/cutevariant/wiki/VQL-language

Example: 

Suppose we have a pedigree of 6 samples with 4 cases and 2 controls.
Select  mutations (heterozygous) which are in case but not in samples. 

```
SELECT chr FROM variants WHERE case_count_het = 4 and control_count_ref = 2 
```
