### ISSUE TITLE
add a variant ID page

### ISSUE THREAD

**Issue by julienthevenon** [labsquare/cutevariant#102]
A helpfull plugin ! 
right click on a variant opens a pane with medical annotations highlighted (list to be defined) and pre-computed ACMG scores. A multi-line text pane should be proposed to add a textual medical interpretation directly in the db.

**Comment by dridk** [comment]
From devel branch, cutevariant support user annotation ( bookmarks, comments and score ). 

![image](https://user-images.githubusercontent.com/1911063/65427481-ae815580-de12-11e9-8de4-d4ab1ded0f15.png)
