### ISSUE TITLE
Support for other assemblies

### ISSUE THREAD

**Issue by klva** [labsquare/cutevariant#107]
Hello,

I'm looking at CuteVariant to analyze variants generated on the hg38 assembly. In the create project dialog, the only assembly option is hg19.  Looking at [the project wizard code](https://github.com/labsquare/cutevariant/blob/14c86b23ee5c53183eaac9ac3cf761bb9944641c/cutevariant/gui/wizards/projectwizard.py#L35), this option seems hardcoded.

Besides adding the option in the project dialog, is cutevariant ready to support other assemblies or would this require significant work ?

**Comment by dridk** [comment]
Hi, 
Thanks for your interessting ! 
Actually it doesn't do anything. You can open any kind of vcf. 
I m working hard on the code to have a beta release soon ! So, any feedback is welcome
