### ISSUE TITLE
Variant view does not refresh when a variant is modified in variant_info

### ISSUE THREAD

**Issue by klva** [labsquare/cutevariant#117]
Steps to reproduce :
* display the "favorite" column in the fields editor
* select a variant in the variant view
* check the "Is saved" checkbox in the variant_info plugin
* click save

Expected behavior :
The favorite value of the variant in the variant view changes immediately

Actual behavior :
The variant does not change until the view is manually refreshed

The fix has to be tested in group by mode as well

**Comment by dridk** [comment]
Now the User variant data can be edited from the context menu . 
![image](https://user-images.githubusercontent.com/1911063/91604490-08699400-e96f-11ea-80b7-e083cd051c87.png)

I disable for now the possibility to save from variant_info. I prefere use it as a viewer only. 
But I keep the possibility to restore the save action from it.
