### ISSUE TITLE
 nested filter UI

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#118]
https://js.devexpress.com/Demos/WidgetsGallery/Demo/FilterBuilder/WithDataGrid/jQuery/Light/

![image](https://user-images.githubusercontent.com/1911063/91630740-3208d680-e9d4-11ea-883a-2d6e8c89ce06.png)

**Comment by ysard** [comment]
Hum it could be a nice evolution, but maybe too optimist for now.
