### ISSUE TITLE
cutevariant console shortcut doesn't work anymore

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#119]
`cutevariant` shortcut installed from setup.cfg doesn't work anymore.

In __main__.py, `main()` should not have arguments. Moreover `__main__` function is legacy here because the way of execution via `python -m cutevariant` is quite deprecated in favor of `gui_scripts` option from setup.cfg. Note that __main__ is not called when the module is imported (https://docs.python.org/fr/3/library/__main__.html).

I will partially revert the change found in ec8e8abfb20fcf73e03621fe5375faab152d2863 (found thanks to an explicit commit name :tired_face:)

**Comment by dridk** [comment]
I probably change this for pyinstaller . Let see if it build correctly from appveyor .

**Comment by ysard** [comment]
Fixed for my shell, please reopen if any issue anywhere...
