### ISSUE TITLE
Edit comment is broken

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#124]
cutevariant/gui/plugins/variant_view/widgets.py

This menu should:
- [x] Load previous comment (currently broken)
- [x] Save comment in DB (ok)
- [x] Refresh variant_info widget after saving (currently broken)
- [x] Update source code when RichText is updated (seems to be currently broken)

![image](https://user-images.githubusercontent.com/14988285/93634129-60386f80-f9f0-11ea-8f95-b919d70c3a4d.png)
- [x] Be documented (currently broken)
- [x] Bold/italic are broken
- [x] Quote/url are not implemented

As it stands, I don't think recreating a text editor is a major or requested feature :o ; it is time-consuming to implement and is blocking for the issues like #123 and later for #122.

**Comment by dridk** [comment]
I was inspired by markdown editor.   Rich text view should not be editable . That's why I used 2 slides 

![image](https://user-images.githubusercontent.com/1911063/93665535-81906e80-fa77-11ea-842d-df91b7189a2f.png)

**Comment by ysard** [comment]
Mainly fixed now... Please just add the current comment text in MarkdownEditor constructor

https://github.com/ysard/cutevariant/blob/ba06dd724083da4f5a41fc423c2485b160e8c902/cutevariant/gui/widgets/markdown_editor.py#L35

editor = MarkdownEditor(default_text="xxx")

**Comment by dridk** [comment]
I cannot fixed this without your pull request

**Comment by dridk** [comment]
id will be hidden from the view, not from the data

**Comment by ysard** [comment]
Ok thx, i close this now
