### ISSUE TITLE
Cleaning files

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#125]
./cutevariant/gui/querymodel.py

This:

![image](https://user-images.githubusercontent.com/14988285/93636416-2f5a3980-f9f4-11ea-9efa-0e3a0a472664.png)

is not possible...

Can we use IDEs that don't allow the developer to leave this sort of thing in committed code?

There is also a technical justification for not loading all modules from the earth: the speed launch of the app.

:cry:

**Comment by dridk** [comment]
I will ! 
The main reason of this : Make it work first , clean after ! :D

**Comment by dridk** [comment]
I cannot read what is written in yellow ?

**Comment by ysard** [comment]
It's unused imports.

> The main reason of this : Make it work first , clean after ! :D

Il y a une multitude de choses à répondre, qui démontrent que ça ne tient ni à moyen terme pour du travail personnel, ni à très court terme pour du travail en groupe.

Un petit nettoyage avant de commiter, une petite doc en s'assurant que les types manipulés soient documentés au moment de commiter une fonction ça prend 10 secondes car on est dans le truc. 3 jours après ça prend quelques minutes car on est déjà passé à autre chose. 3mois après ça prend 10 minutes.
10 minutes x 50 fonctions ça fait des heures. 

Pire encore si la doc n'est pas mise à jour après une modif du code ou copiée collée sans attention d'une autre fonction (ex: c'est documenté comme recevant un dict mais ça reçoit en fait un tuple), ou si la doc est partielle (ex: `variable_name(TYPE): variable name` => le truc est +/- généré automatiquement mais rien n'est utilisable; or comme il y a quelque-chose d'écrit, les linters ne relèvent pas le problème et on a aucune chance de retourner dessus un jour sauf quand on en aura besoin en urgence).

Si c'est pas toi qui a codé les trucs et si tu passes d'appel en appel de fonctions non documentées non plus, c'est directement minimum 10minutes par fonction à documenter. J'en suis réduit parfois à faire des grep sur tout le projet pour tracer les usages d'une fonction. Autre exemple avec mon parseur Bed, le truc est documenté et pourtant tu l'as réimplémenté, imagine si je ne l'avais pas documenté => encore moins de chances de le réutiliser...

C'est impatchable à moins de ne plus compter son temps; or le temps est précieux autant pour un thésard que pour toute autre personne bénévole ou employée sérieuse... 

**On a pas les moyens de faire du vite fait et du pas cher. Les autres oui, c'est même la justification de leurs salaires (à défaut  d'autre chose)** (faire et défaire c'est travailler).

Essayons de ne pas recréer les mêmes tas de code que ceux produits autour de nous (pas seulement en bioinfo).

**Comment by ysard** [comment]
Done; until next time.
![shame](https://media.tenor.com/images/b7795b796da4711ce70de48c18cdec6e/tenor.gif)
