### ISSUE TITLE
What is the purpose of Edit menu ?

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#129]
mainwindow:
```
 def copy(self):
        pass

def paste(self):
        pass

def select_all(self):
        """Select all elements in the current tab's view"""
        self.current_tab_view().view.selectAll()
```

and `current_tab_view` is commented out => exception raised.

It is so frustrating for a user to have a completely non-functional feature or a partially implemented feature.

Can we purge this menu ?

**Comment by dridk** [comment]
We can use it to add "copy" , "select all" line !  Or other edit action from variant_view plugin
