### ISSUE TITLE
Columns issues in variant_view plugin

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#131]
- [x] Default field were (master branch) pre-selected.
There is nothing more annoying to select the fields one by one on each restart

- [x] Why id column is showed ? It was hidden in master.
who cares about the id of the variant in BDD?

**Comment by dridk** [comment]
It should be hidden, yes!  It's for debugging purpose actually. It can be hidden now .

**Comment by ysard** [comment]
- Ok for id column, i will display it only in DEBUG loglevel.
- For default selected fields i will let you fix that.

**Comment by ysard** [comment]
Id do not see where i can filter this id column.

You can auto filter it according to the loglevel with this code

```
from logging import DEBUG
...
if LOGGER.getEffectiveLevel() == DEBUG:
...
```

**Comment by dridk** [comment]
Default fields works here ! They are defined in state.py

**Comment by ysard** [comment]
Ok, can we think about a set of pre-defined and useful fields other than the current ones ?

Also, a plugin/part of plugin to save these display settings...
