### ISSUE TITLE
Installation/dev on Windows

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#134]
Sections were purged from the README in master...

It's a shame for someone who wants to build the project on this platform.
Time has been invested to make it work.
Please do not delete documentation unilaterally...

In addition, the section concerning zest releaser has also been deleted.
I hope that the upload process to pypi does not just involve a manual modification of the __init__.py...

**Comment by dridk** [comment]
Pyinstaller has been updated recently to make building PySide2 application on win32 easier.
That's why I changed it. 
Actually, the windows binary is created from appVeyor automatically.

**Comment by dridk** [comment]
Automatic build of windows binary is avaible here : 
https://ci.appveyor.com/project/dridk/cutevariant-1ex8i/build/artifacts
