### ISSUE TITLE
Sqlite run asynchronously

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#135]
It would be greate to use asynchrone sqlite query to perform slow operation like : 

- Count how many variant there are 
- Load variants into the mainview 

@ysard  I did this class  ..   Could you review it and tell me if it is okay for you ? 
https://github.com/labsquare/cutevariant/blob/devel/cutevariant/gui/sql_thread.py

**Comment by dridk** [comment]
https://www.learnpyqt.com/courses/concurrent-execution/multithreading-pyqt-applications-qthreadpool/

**Comment by ysard** [comment]
I will check this in a few moment. The priority is to fix most plugins (you know that there are many problems here !).
New functionalities like this should be on a separated branch.
We need to make the devel branch great again, i.e. an active dev branch ahead of master but free of obvious bugs as much as possible.

BTW: Async in Python should be done with asyncio. I have never tested it yet; but it looks powerful and dedicated to it.
Honestly i still use futures (http://sametmax.com/en-attendant-asyncio/)...

Have fun:
http://sametmax.com/tag/asyncio/

Please try to stay focused on fixing existing bugs...

**Comment by dridk** [comment]
Create issue for bug and assign me. I will fix it quickly. I already fixed some of them

**Comment by dridk** [comment]
This feature is solved now with new SqlRunnable class . Here is how it works : 

# Synchrone 
```python
conn.execute("SELECT COUNT(*) FROM variants" ) 
```

#  Asynchrone equivalent 
```python
def long_sql_query(conn):
      return conn.execute("SELECT COUNT(*) FROM variants")

# Create runnable
runnable = SqlRunnable(conn, long_sql_query)
# connect finished signal to show_result
runnable.signals.finished.connect(show_result)
# execute function in a new thread
QThreadPool.globalInstance().start(runnable)

def show_result():
     print(runnable.results)



```

**Comment by dridk** [comment]
Some fixed requirements about pagination . But Asynchron is ready  !

**Comment by ysard** [comment]
Are you really 100% sure of what you are doing ? (No offense here!)
I'm really surprised by a straightforward implementation based on a single connection shared across multiple threads.
Maybe your are playing with fire here :p

- The documentation strongly forbids this implementation:

https://docs.python.org/3.7/library/sqlite3.html#multithreading

> Older SQLite versions had issues with sharing connections between threads. That’s why the Python module disallows sharing connections and cursors between threads. If you still try to do so, you will get an exception at runtime.

- Even if your code doesn't raise any runtime exceptions, what type of biologist suicide barrier have you implemented to ensure that 2 simultaneous requests do not write to the database at the same time?
The doc suggests that this case causes database corruption.

Normally we use cursors (transactions) for every write queries. This should limit the risks but I'm not sure that this excludes them at 100%.
Older versions of SQLite provide cursor and connection objects that are clearly not thread safe:
https://openclassrooms.com/forum/sujet/python-sqlite-et-multithread-78211

See:
https://stackoverflow.com/questions/393554/python-sqlite3-and-concurrency

About the `check_same_thread` argument in the doc:
https://docs.python.org/3.7/library/sqlite3.html#sqlite3.connect

> By default, check_same_thread is True and only the creating thread may use the connection. If set False, the returned connection may be shared across multiple threads. When using multiple threads with the same connection writing operations should be serialized by the user to avoid data corruption.


- I agree this should avoid freezing the UI for long queries. But a DB of few millions of records is not a big DB. Threading must not forget that queries can be optimized.
Unfortunately I don't have enough time to do better...

Other resources:

Making sqlite slower in python by using threads: 
https://gist.github.com/jamesls/1f7a323f042089b4bc33

https://python.developreference.com/article/14053942/Getting+SQLite3+to+work+with+multiple+threads

**Comment by dridk** [comment]
yes I know ! If you check the code carefully, you will see I am not sharing the same connection. I create a new one from the filename. 
https://github.com/labsquare/cutevariant/blob/9a36f56d34c52bf31bf6cf63db919b7bf9773a28/cutevariant/gui/sql_thread.py#L21

So, I hope reading a sqlite file from 2 differents connection do not create race condition.

**Comment by ysard** [comment]
Ok!
- 1 new connection per thread is OK
- SQLite is not made for concurrent access but for our use cases (not 10 simultaneous users) it will be ok
- Maybe a decorator to transform sync functions to async will be perfect
