### ISSUE TITLE
VQL command module = pain in the ass

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#137]
- [x] Can someone document this module ?

What is the purpose of `execute_all /execute` functions (never used)?
`create_command_from_obj()` seems to wrap other functions but in `cutevariant/gui/plugins/vql_editor/widgets.py`
`run_vql()` calls it only for "create_cmd", "set_cmd", "drop_cmd".

- [x] These functions are not tested by unit tests.
- [x] The unit tests module is also not documented.

I can't maintain this bunch of code...

**Comment by dridk** [comment]
Command module contains the interface between VQL  and sqlite database.
Each command function, correspond to a VQL query.
For instance : 

" SELECT chr, pos FROM variants " ===>  select_cmd()
"COUNT from variants" ===> count_cmd() "

execute(vql)  is a function to run a command from a vql query : 

```python
cmd.execute(conn, "COUNT FROM variants") 
# Or 
for variant in cmd.execute(conn,"SELECT chr FROM variants") : 
     print(variant)

```

Let me adding documentation right now ! Sorry ... !

**Comment by dridk** [comment]
By the way, they are all tested : 

```bash
tests/test_command.py::test_select_cmd PASSED                                                                                                                                                                                         [  1%]
tests/test_command.py::test_select_cmd_with_set PASSED                                                                                                                                                                                [  2%]
tests/test_command.py::test_create_cmd PASSED                                                                                                                                                                                         [  3%]
tests/test_command.py::test_count_cmd PASSED                                                                                                                                                                                          [  4%]
tests/test_command.py::test_drop_cmd PASSED                                                                                                                                                                                           [  6%]
tests/test_command.py::test_bed_cmd PASSED                                                                                                                                                                                            [  7%]
tests/test_command.py::test_set_cmd PASSED                                                                                                                                                                                            [  8%]
tests/test_command.py::test_import_cmd PASSED                                                                                                                                                                                         [  9%]
tests/test_command.py::test_create_command_from_obj PASSED                                                                                                                                                                            [ 10%]
tests/test_command.py::test_execute PASSED                                                                                                                                                                                            [ 12%]
tests/test_import.py::test_import[FakeReader] PASS

```

**Comment by ysard** [comment]
Thank you !
Ok , it's execute and execute_all that are not tested (maybe not important?).

Note: be careful with auto-generated docstrings: "Description" value is just a default value... Linters will be probably ok with that but humans not :p


I see heavy code duplication here:
command.set_cmd vs sql.create_selection_from_sql
and
create_cmd vs sql.create_selection_from_sql

=> **I'm working on it.**

---
Also, another question here:
I see "count=0" here: https://github.com/labsquare/cutevariant/blob/55aa1c96e13ec90e1872ecb8ee5ca0fe8c38528b/cutevariant/core/command.py#L197
But count is redefined just below https://github.com/labsquare/cutevariant/blob/55aa1c96e13ec90e1872ecb8ee5ca0fe8c38528b/cutevariant/core/command.py#L234

When this function can receive such a value ? It is not tested.

Also `count = 0` will be misinterpreted here:
https://github.com/labsquare/cutevariant/blob/55aa1c96e13ec90e1872ecb8ee5ca0fe8c38528b/cutevariant/core/sql.py#L348

Maybe i should test None here ?

In fact, what is the use case of a count = 0 here ? Is it a default value, a logical value for the use case or a random value ?

**Comment by dridk** [comment]
Counting variant from SQL may be time consumming. That's why I store count into sql table selections. 
The parameter "count" must be used to avoid counting from sql.

**Comment by ysard** [comment]
Ok
