### ISSUE TITLE
IDE conf

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#138]
There are non breaking spaces inserted everywhere in files.

Like you can see, it's quite "annoying":
![image](https://user-images.githubusercontent.com/14988285/93795929-67eb5480-fc3a-11ea-9d42-848757c7eac5.png)

Please configure your IDEs/notepad.exe :sob: 
I will insert a special directive in the Makefile if it is not possible...

**Comment by dridk** [comment]
I used black only ! Seems it doesn't remove breaking space !

**Comment by ysard** [comment]
Ça reste conforme aux PEP, black ne fait pas de correction d'ordre orthographique dans les docstrings et commentaires, n'empêche que c'est dégueulasse quel que soit le langage :p
Pourquoi ton IDE fait-il ça :crying_cat_face:

**Comment by dridk** [comment]
je pense que c'est parce que je jongle entre linux chez moi et windows au
travail
