### ISSUE TITLE
Plugins doc

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#141]
We should think about writing a usage doc for all the plugins... You are dealing with biologists not geeks :p
In my upcoming changes i added a variable "__long_description__" to every plugins. It will be used to display a full help on demand.

Can you initialize a *frama thing* to start writing some help ?
In french for a better starting.

- [x] fields_editor
- [x] variant_view
- [x] vql_editor
- [x] filters_editor
- [x] source_editor
- [x] variant_info
- [x] word_set

**Comment by dridk** [comment]
I did a VQL doc here
https://github.com/labsquare/cutevariant/wiki/VQL-language

**Comment by dridk** [comment]
Do you want to add "WhatsThis" to all relevant button ?

**Comment by ysard** [comment]
Its a big work, i'm starting to seriously run out of time for the rest of my stuff, but that's the idea.

The problem is that these tooltips will overload the code, they should be in separated files (especially for plugins) from which we import the variables.

In this case it seems difficult to translate them with Qt because we are outside QObject?

**Comment by ysard** [comment]
Done; see last commits in https://github.com/ysard/cutevariant/tree/doc

If someone modifies these docs, PLEASE make sure to update the translations (`make translations`).
