### ISSUE TITLE
plugin source_editor: fully broken

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#144]
- [x] Plugin was broken since the refactoring: sql connection was not updated and Bed file import was broken
=> see a6d98d6bac90ca2710f1507f78f69254aba5d98b

- [x] Selection class is is no longer available in the module `sql`
https://github.com/labsquare/cutevariant/blob/2a0ea9c2379a9fc9422278c4901961a5f04e440a/cutevariant/gui/plugins/source_editor/widgets.py#L346-L383

It's such a shame to have worked on these functions which worked perfectly and which must be fixed now :(

- [x] Also, there was a misunderstood in the API of `create_selection_from_sql`; selection id was returned by error, but it was functional. It is now official in 80096e86799d646bc8ee1ae5ed6dc503d4a29b40.

BUT! when the selection creates nothing (empty result of set operation), the selection is not created and i'm doing a DB rollback.
I think it's better to alert than to put the user in front of an empty list of variants.
So, could you display an alert to the user in this case?
"the selection of variants created is empty, please review your set operation"

- [wontfix] I will implement an a self-naming of an intersection with a BED file with the name of this file to facilitate its identification.
The user can always rename afterwards. What do you think ?

**Comment by ysard** [comment]
Note: I can't merge for now, new SQL threading seems to be in testing on devel. I prefer to stabilize the devel branch without new feature....

**Comment by dridk** [comment]
Selection class has been replaced by functions. So, sql module contains only pure function which sounds better. 

I agree to avoid saving an empty selection. Lets add a message as you said

About naming, a simple QInputDialog can ask the name of the selection. Using bedfile name doesn't allow to make different bed intersection using the same bed file.

I guess it should be possible to make all of these plugin operation from command module. There are 3 kind of CREATE command corresponding to the following VQL : 

- save current query as selection
CREATE boby from variants where....

- create a selection from bedfile
CREATE boby from source intersed bedfile

- create from set operation
CREATE boby = a + b

About asynchrone features, it is on a dedicated branch

**Comment by ysard** [comment]
- Different intersections with same bed ? Is there any constraint in the name of a selection, or is it just a matter of user confusion with multiple selections with the same name ?

- Ok for set op, =>** I will try to fix this one as soon as possible**

- Ok, for async features in separated branch (didn't see sorry)

**Comment by dridk** [comment]
For instance: 

Create A from variants where...
Create B from variants where ...

Create A2 from A Intersect "my.bed"
Create B2 from B intersect "my.bed" 

Selection name must be unique. Here we have 4 selections A,B,A2 and B2.

**Comment by ysard** [comment]
Ok, 

```
  File "cutevariant/gui/plugins/source_editor/widgets.py", line 366, in _make_set_operation
    selection_1 = sql.Selection.from_selection_id(record_1["id"])
AttributeError: module 'cutevariant.core.sql' has no attribute 'Selection'
Traceback (most recent call last):
  File "cutevariant/gui/plugins/source_editor/widgets.py", line 420, in edit_selection
    old_record = self.model.record(current_index)
  File "cutevariant/gui/plugins/source_editor/widgets.py", line 124, in edit_record
    if sql.edit_selection(self.conn, record):
  File "cutevariant/core/sql.py", line 509, in edit_selection
    "UPDATE selections SET name=:name, count=:count WHERE id = :id", selection
sqlite3.IntegrityError: UNIQUE constraint failed: selections.name
```
Constraint is here, but in GUI

I'm working on the first part of the issue

**Comment by ysard** [comment]
Should be fixed now; To be tested... and reopened...
