### ISSUE TITLE
Edit menu

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#145]
I think it should be moved into the popup menu over a variant in variant_view.

A user directly understand what is the purpose of copy/select all here.
In main window its confusing.

Also:
- [x] Doesn't work without error showed to user if UI is grouped => working on it
- [x] Copy issue
https://github.com/labsquare/cutevariant/blob/74b2784ae5a0a9d1f45910ad67e009bc9c548a29/cutevariant/gui/plugins/variant_view/widgets.py#L824
Since Python 3.7 dictionaries are ordered; it is not the case before. There is absolutely no guarantee that the order is the same from a run to another.
It is a "killing feature" :p

- [x] We should avoid context menu on second_pane => working on it
- [x] Copy/select all should be moved in VariantView widget => working on it

And:
Do you really want that users can use excel with Cutevariant ? :p

**Comment by dridk** [comment]
Ok, to move Edit action to the variant_view context menu . Or maybe, we can keep both ? 
Yes, copy past to excel is a good features for biologist . 
You assigned me on this request but you write "working on it" .

**Comment by ysard** [comment]
Ok both will be kept for now :p
Desassigned :p

**Comment by ysard** [comment]
This should be fixed now in upcoming changes; See variant_widget related commits
