### ISSUE TITLE
Arguments for Merging annotations and variants tables 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#146]

**Comment by ysard** [comment]
C'est un concours ?
> L'homéopathie est la médecine du futur, au même titre que la méditation pleine conscience, le yoga ou la sophrologie.

J'ai gagné ?

---

Évitons la désinformation sur la dé-normalisation des bases.

http://letmegooglethat.com/?q=SQL+join+costs

https://www.quora.com/How-evil-is-SQL-Join
> JOINs in SQL are described as evil by junior developers who don’t understand relational database management systems. JOINs incur a CPU cost, which is greatly emphasized when the data volume grows large and there are no indexes on the columns participating in the JOIN operations. I would expect the type of person to claim that JOINs are evil to be someone who doesn’t understand RDBMS architecture.


https://stackoverflow.com/questions/5773611/how-costly-are-joins-in-sql-and-or-whats-the-trade-off-between-performance-an
> Yes, joins have a cost, there's no getting around that. However, the cost is usually a lot less than you'd think, and can often be swamped by other factors like network transmission times. By making sure the relevant columns are indexed properly, you can avoid a lot of those costs.


> ALWAYS ALWAYS prefer normalization. It is appalling to me that denormalization STILL gets this kind of attention.
NORMALIZE - thats what the database engines are tuned for.

> Three or four joins in a query is certainly not any reason to de-normalise the tables to try to improve performance. As comparison; for our web site we are using a de-normalised table to read from, because we would need about 40 joins to gather the data that we need.


Faut-il des chiffres ?
https://www.brianlikespostgres.com/cost-of-a-join.html

> Even with a query that already joins 150 tables w/ 100k rows each, adding another table is only an additional 1.2 ms increase. Cool!
> we get great performance with our million row tables as well. But still, joining 50 tables with 1M rows each, in just 12ms. Wow!


Référence tuto FR incontournable pour savoir de quoi on est en train de parler:
https://laurent-audibert.developpez.com/Cours-BD/?page=bases-de-donnees-relationnelles

Et comme on dit:
> Stop guessing, Measure !

---
Du coup on peut soit dénormaliser, et donc si ce n'est ralentir les requêtes (à défaut de gagner 1ms par requête), à coup sûr rendre le traitement des données plus complexe. Donc encore refactoriser tout le code.
Ou: Corriger les fonctionnalités ou en apporter de nouvelles.

**Comment by dridk** [comment]
Après, moi je trouve autant de liens qui disent le contraire . En particulier avec sqlite. Car je vois ça comme un equilibre entre performance et espace.   Une base dénormalisé sera bcp plus rapide.  

Mais bon, tu as raison sinon ! On va pas tout changer. Et tt façon, avec l'asynchrone, ca ne pose pas vraiment problème. 
Faut juste voir si ca pose pas problème avec les sets sur des annotations.
