### ISSUE TITLE
Cannot group by samples

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#147]
when sample fields is here, it is not possible to use group by . 

`SELECT chr, pos , sample["boby"].gt GROUP BY sample["boby"].gt` doesnt work

**Comment by ysard** [comment]
Have we a sample file to test this ?
Variant_view has been refactored on my branch, maybe this issue is solved

**Comment by dridk** [comment]
See also this commit : 
https://github.com/labsquare/cutevariant/commit/96b6b0a8a7f71b04d740a38513b009f56172473d

**Comment by dridk** [comment]
Need some test for this feature  ! 

By the way, filter editor with sample field from VQL also work
