### ISSUE TITLE
ped parser in wrong place

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#149]
cutevariant/core/importer.py

`import_pedfile()` should be moved in a reader in `cutevariant/core/reader/`

**Comment by dridk** [comment]
reader/ folder was dedicated first for AbstractReader subclass only. 
But yes, we have BedReader, we can have PedReader. 
To select children from AbstractReader, we can loop over the folder and detect the type.

**Comment by ysard** [comment]
See https://github.com/ysard/cutevariant/tree/ped_refactor
