### ISSUE TITLE
variant_view plugin: cross database links

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#150]
- This functionality is dead
- Can we provide example of urls pointing to databases of variants ? (I need examples)
- We should restore variant popup menu if these databases shortcuts

**Comment by dridk** [comment]
varsome
https://varsome.com/variant/hg19/15%3A68500735%3AC%3AT

dbsnp 
https://www.ncbi.nlm.nih.gov/snp/?term=NM_000237.3%3Ac.1421C%3EG+NG_013007.1%3Ag.7147G%3EA

google

genecards ( gene)
https://www.genecards.org/cgi-bin/carddisp.pl?gene=ACE2

IGV
https://software.broadinstitute.org/software/igv/ControlIGV

**Comment by ysard** [comment]
Problem for your varsome example:
chr15-68500735-C-T

How can i deduce the HGVS notation:
c.679G>A

Is 679 the position ? But what is 68500735 in this case ?


Also HGVS notation includes deletion/insertion/duplication, etc.
https://www.hgvs.org/mutnomen/recs.html

Complex cases to implement in a context menu...

[edit]:
HGVS notations are in annotations table; is it worth to query this table during context menu popup ? Or should we wait that a user displays these fields...
=> I'm retaining this last idea

[edit2]:
ncbi rules:
https://www.ncbi.nlm.nih.gov/variation/hgvs/

> "c.123T>C" will not be accepted: The expression must provide the reference sequence on which the  numbering system is defined. Ideally, the expression should contain an  NCBI RefSeq accession and version, e. g. NM_001234.3:c.123T>C

=> don't know where to get this reference sequence number

**Comment by dridk** [comment]
many way to identify a mutation:

- genomic location 
relatif to human genom reference. The first position correspond to the top of the short arm chromosome. 
(hg19)g.chr3:444553A>C 

- coding location 
relatif to the gene transcript. The first position correspond to the "A" from the first coding codon "ATG" 
(NM_xxxx)c.23A>C 
this is stores into hgvc_c annotations tables if it is avaible. 

- snp id 
using dbsnp id : rs34453335

For context menu,  I suggest to create default links only only with chr, pos, ref, alt.

**Comment by ysard** [comment]
Okey;

About: hgvc_c annotations, i have no NM_xxxx ids; and the ncbi requires this reference sequence...
Maybe real annotated files haven't this issue...

For now, menus are activated according to the columns that are displayed. No exceeding queries.

**Comment by ysard** [comment]
Close for now 3 menus are dynamically available; it's sufficient for now.
