### ISSUE TITLE
ped files

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#152]
- [x] ped file is always "imported" even if PED import is skipped (multiple .ped files created in /tmp/ and never deleted).
Import of PED file should not be systematic especially when no changes are made to the PEDView
=> let the basic process of importing samples work alone!

- [x] If we specify data in the SamplePage/PedView, there are errors:

![image](https://user-images.githubusercontent.com/14988285/94956293-38670280-04ec-11eb-836b-f4e86b6950c2.png)

```
Traceback (most recent call last):
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/model_view/pedigree.py", line 200, in get_pedfile
    self.model.to_pedfile(outfile)
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/model_view/pedigree.py", line 72, in to_pedfile
    file.write("\t".join(sample) + "\n")
TypeError: sequence item 2: expected str instance, NoneType found

Traceback (most recent call last):
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/model_view/pedigree.py", line 200, in get_pedfile
    self.model.to_pedfile(outfile)
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/model_view/pedigree.py", line 72, in to_pedfile
    file.write("\t".join(sample) + "\n")
TypeError: sequence item 2: expected str instance, NoneType found
```
- [x] Note that we have to double click on each item like showed on the above image to let the dialog box appears.
And the "fam" option of mother_id and father_id disappear immediately after selection.

- [x] During insertion, what are these logs :

```
Compute case / control
controls are 
cases are 
```

- [ ] Global confusion accross the project: "sample" or "sample_name" with "individual_id" field of sample.
=> its really confusing when debugging/reverse engineering...

- [x] Select manually an empty field in the view conduct to the following PED file:
`fam NORMAL  TUMOR   None    2   1`

- [x] We should not allow users to import or build via the view samples with individual_id in their father or mother identifiers.
=> parthenogenesis is not common in humans (yet)

- [x] family_id instead of father_id/mother_id in combobox

Summary:
This is not functional, and not documented, users do not know what to do during these steps and errors are not showed. Can we just remove all of this test code ?

**Comment by dridk** [comment]
Pedigree is used to compute extra variant fields like case_heterozygous_count ( nombre de cas/temoin ou le variant est heterozygote)
So this is an important features similiar than SnpSift CaseControl.

fields are computed here: 
https://github.com/labsquare/cutevariant/blob/d461416f0fa4b5862f8f44ffd435c71cae3cf56c/cutevariant/core/reader/abstractreader.py#L311



https://pcingola.github.io/SnpEff/
ss_casecontrol/

It works actually. Except some bug you notice here. Let me fix that 

I take this issue. I will fix it

**Comment by ysard** [comment]
J'ai un problème d'unicité ici:
https://github.com/labsquare/cutevariant/blob/d461416f0fa4b5862f8f44ffd435c71cae3cf56c/cutevariant/core/importer.py#L165-L167

Je déduis qu'un sample est censé être référencé avec le couple (family_id, individual_id) d'après la doc (https://www.cog-genomics.org/plink/1.9/formats#fam).

N'est-il pas risqué de n'utiliser que l'individual_id (colonne name chez nous) ?

Imaginons 2 familles distinctes: Micron et Valse, avec respectivement 1 Emmanuel chacun.
2 Emmanuel; c'est trop, cette ligne va en écraser un. Ça serait dommage...

Si le family_id doit être pris en compte dans l'unicité, alors celui du fichier PED importé ne peut mettre à jour le family_id par def de la BDD (fam).
Concrètement, un PED est-il lié à des données de séquençage et les family_id doivent-ils concorder ?
Si oui, j'implémente une contrainte, si non 2 personnes qui s'appellent pareil vont poser problème.

See: https://github.com/ysard/cutevariant/tree/ped_refactor

**Comment by dridk** [comment]
Les identifiants d'individu d'un fichier ped correspondent au "samples" du fichier VCF qui sont censé être unique.  
Du coup, il faudrait juste verifier que les identifiant sont unique. Ca résoudrait le problème . 
En pratique on se sert rarement de la famille.  Mais ca peut être utile pour des analyses ulterieurs.

**Comment by ysard** [comment]
> Les identifiants d'individu d'un fichier ped correspondent au "samples" du fichier VCF qui sont censé être unique.

Ok c'est le point important. Si les fichiers sont couplés, il n'y a pas d'opposition à contraindre l'unicité des couples family_id, individual_id. Ne pas le faire serait prendre un risque d'avoir des erreurs.

Je trouve des docs plus catégoriques sur ce fait:
https://www.well.ox.ac.uk/~cfreeman/software/gwas/gtool.html

> The --family flag is used to create a unique ID_1 (and identical ID_2) from the Family ID and Individual ID in the PED file, 'Family ID'_'Individual ID'.

J'ajouterai la détection de doublons quand même car on ne peut être à l’abri d'avoir 2 personnes avec le même prénom dans une même famille.

Nous utilisons un family_id qui est "fam" par def; j'espère que dans les vrais fichiers c'est aussi le cas ou qu'il est toujours renseigné.
Dans le fichier de test .tfam, le family_id est "Fam1".

**Comment by dridk** [comment]
dans les vrai fichiers, c'est principalement des identifiants anonyme. en
tout cas a lhopital .

**Comment by dridk** [comment]
@ysard pourquoi tu commit pas direct sur mon Dev ? Y a rien à craindre, elle est pas en prod

**Comment by ysard** [comment]
Si tout le monde a le même id d'anonymisation c'est bon.

@dridk: J'attends que mes modifications soient stables; mais présentement je n'ai pas revu le contenu du merge SQL threading: Y'a des trucs bizarres genre la classe SqlRunnable dupliquée dans 2 fichiers sql_runnable.py et sql_thread.py

**Comment by dridk** [comment]
Sql_thread.py est a jeté .. .C'est sql_runnable

**Comment by dridk** [comment]
Toujours une erreur qd on deroule Father_id / Mother_id... 
A explorer

**Comment by ysard** [comment]
Rien modifié de mon côté concernant les PED c'est encore une branche séparée qui semble stable toutefois.

[edit]:
Après je ne comptais pas modifier le comportement du Wizard; il y a des choses à revoir de ce côté pour faire qqchose de propre mais je n'ai pas le temps.

**Comment by ysard** [comment]
Add some new errors found. I'm refactoring the code, you are making me CRAZY. pedigree.py is NOT documented I'm doing reverse engineering on a project that is few weeks old!

But...
> It works actually™

Ex: 2 hours lost to explain why 2 ped files are systematically created when a Wizard is launched.
=> addPage method seems to explore properties in self.field and this is calling get_samples of PedView for nothing.

> Toujours une erreur qd on deroule Father_id / Mother_id...

Yes its here:
https://github.com/labsquare/cutevariant/blob/73c3c6f3bc00049f1f72ced710ec8c9e3c101fc0/cutevariant/gui/model_view/pedigree.py#L150
0 is the column of family_ids not individual_ids (col 1) (=> don't touch this, i'm on it on my branch)

We have magic values for PED columns everywhere, SO, IT IS confusing...
I think my PedReader should return a keyed dict, not a list... It will be much easier to debugging things like this.

**Comment by ysard** [comment]
I close this "casus belli" issue because this functionality is operational (It works™).

- However my last comment on a keyed output instead of a list is still valid.
- Likewise for the name vs individual_id confusion is still present even if all the other fields are henceforth compliant with the PLINK standard;
