### ISSUE TITLE
prepare the release

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#155]
- [x] release to master
- [x] release to pip 
- [x] create a gh-page
- [x] add issues to mendel milestone
- [x] autorelease windows binary from appveyor

**Comment by dridk** [comment]
I think we should merge on master and release a version on pip. Because the actual pip version doesn't work.

**Comment by ysard** [comment]
Ok there are 2 days to test the app and find the last bugs.

If the schedule is respected, on the 30th you will be able to merge on master and I will be able to "shut down the computer and resume normal activity/life/whatever".

**Comment by dridk** [comment]
Thanks a lot ! 
I have a new stagiaire who is going to work on it !

**Comment by ysard** [comment]
A trainee; hum I will write a set of contributing rules... :scream: :p

**Comment by ysard** [comment]
Last set of commits for this release with important fixes (GUI bugs, refreshing of plugins, selection problems, cache improvements, filters errors, documentation, etc.)

After more than a month, more than 600 commits and more than 450 hours spent, I think the project is functional, again ...
Sorry for the mood swings, but I should have spent significantly less time on all of this.

I spent a lot of time testing, but bugs can still be hidden; **I also think that a merge on master is now possible.**
Version is updated to "1.0.0beta0"; it's a major release.

I will finish writing a contribution guide ...

**Comment by dridk** [comment]
Thanks for all !! Its not a useless work ! 
I will start to write a paper right now with the release !

**Comment by dridk** [comment]
I release to master and pip ! 
I m confused with make full release .. So here what I did : 

- git checkout devel
- make fullrelease 
- git checkout master
- git merge devel 

But I am not sure it's the good way. Because It auto tags and push ... ! 
I can give your pypi access if you want .

**Comment by dridk** [comment]
So the good way is to merge into master first !

**Comment by ysard** [comment]
Or release to devel with a name x.x.x.yyy.devx
and on master with a name x.x.x.rcx or x.x.x

Nevertheless, it's ok :+1:
