### ISSUE TITLE
[ variant_info] error when no annotation

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#158]
variant_info raise error with raw vcf without annotation. nothing appear in genotype.. 

Please load data if available and catch the exception.

**Comment by ysard** [comment]
Yes, broken...
In fact what is the purpose to retrieve annotations and samples from `get_one_variant` ?
This seems not used and this is why the exception is raised...

**Comment by dridk** [comment]
I want to display all relevant information of a variant when selected one

**Comment by ysard** [comment]
As long as the right column is not selected in fields, i think a user has no use of it:
Only if column is displayed => data can be selected.

Ex: We do not copy all data related to a variant (annotation/sample) in clipboard.

**Comment by ysard** [comment]
Current state is a dup of #165
