### ISSUE TITLE
Compile a windows binary

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#16]
Using cx_freeze on Appveyor should work : 
https://www.appveyor.com/

**Comment by dridk** [comment]
https://github.com/fredrikaverpil/fbs-tutorial

**Comment by ysard** [comment]
Standard pip packaging on Windows is fixed.
Directives and rules to build cx_freeze blob on windows are added.

As usual I strongly advise against this kind of practices to create blobs of several hundred MB (350MB here) from applications of a few hundred KB.

That's the way the world works.  Unable to create packaging standards or use existing ones.
Add unnecessary techno overlays. This is the future.

    print(u"Et moi %s {0} %s chier".format("me") % (u"{evol} %s".format(evol=u"l'évolution"), b"fait".decode()) % u"ça")

![image](https://user-images.githubusercontent.com/14988285/57963777-04f0fb80-792a-11e9-8997-f03d6883adcf.png)

**Comment by dridk** [comment]
T'as réussi à le faire marcher sur windows ?? AppVeyor peut générer les binaires et les uploader .(artifact)

**Comment by ysard** [comment]
Oui oui quelques conrrections, pas de difficulté particulière. Faut juste que le .exe sans dans la %PATH% de l'utilisateur.
Le cx_freeze par contre a été bien chiant. Il s'interface très mal avec le setup.cfg et le MANIFEST.in.
Et la version 5.x est incompatible avec Python 3.7; il faut prendre la version 6.x sur GitHub:

    pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master

Pour une archive de 350Mo, et je ne pense pas que limiter les imports dans le code en enlevant les import * puisse avoir un effet là dessus. Bref encore un bel outil de "packaging" :p.

**Comment by dridk** [comment]
Super !!
Faudra l'automatiser sur AppVeyor !
