### ISSUE TITLE
[plugin:variant_view] Async bug; regression

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#161]
In dev branch, when a group is made, the first item is selected and thus the second pane is refreshed.

Since async, the selection of the first item is made before the receiving of the query result by the UI.
=> the second pane is not refreshed accordingly to the first pane data.

**Comment by ysard** [comment]
This commit ea95fedc464ff080e07fad75579159491427ac5e depends on this issue.

Grouping is currently broken in async version of Cutevariant.
You are not solving the pb with this commit :p

It is a nonsense to group variants and still have all of them in the right pane. The resolution of this issue will solve it.
Only the variants in the selected group should be displayed in the right pane.

**Comment by dridk** [comment]
I cannot reproduce the bug . Do you have a procedure ?

**Comment by ysard** [comment]
Yes:
- Load Cutevariant
- Open project (test test.snpeff.vcf for ex)
- Click on group by, its chr by def
- left pane is opened with 1 group (all variants are for chr 11 => it's ok)
- click on FieldDialog, add "pos" to the checked fields
- now there are 11 groups on the left (logic, all positions are unique)
- but there are also 11 variants on the left.

Expected:
- the first item of the left pane should be selected by default, and the unique corresponding variant on the right should be displayed.

- Also, chr and pos columns should be removed from right pane because they are redundant compared to the left pane which already displays them.


I'm fixing this, it's async related because the selection of the first item is made before async queries are done.
