### ISSUE TITLE
[plugins: variant_info, variant_view] Tooltips for descriptions of fields

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#162]
Currently:
- [x] tooltips on variant_info, only on values => should be also on keys
- [x] tooltips on variant_view, contain... the value, not the description of the field.

Also:
- [x] Many typos should be fixed in the text of various descriptions (unclear sentences).

**Comment by dridk** [comment]
About variant_view, the tooltip should be on the header.  
This can be done from VariantModel.headerData  ! Example here : 
```

    def headerData(self, section, orientation, role):
        if role == QtCore.Qt.DisplayRole:
            if orientation == QtCore.Qt.Horizontal:
                return QtCore.QString("Palette")
            else:
                return QtCore.QString("Color %1").arg(section)

        if role == QtCore.Qt.ToolTipRole:
            if orientation == QtCore.Qt.Horizontal:
                return QtCore.QString("Horizontal Header %s Tooltip" % str(section))
            else:
                return QtCore.QString("Vertical Header %s Tooltip" % str(section))

```

**Comment by ysard** [comment]
Done for tooltips; Last thing to do: Fix typos an sentences of descriptions... I'm adding you @dridk

**Comment by ysard** [comment]
Tried to fix few typos...
