### ISSUE TITLE
row color for favorite variant

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#166]
it may be good to displayed "favorite" information even if "isFavorite" field is not selected. 
For instance, each favorite row can be draw with bold text or a background color.

**Comment by ysard** [comment]
Maybe also a shortcut or a pre-registered selection/filter to directly display favorites.

Honestly if a user unchecks the favorite field, it is because he doesn't use this information. It's like genes in context menu...
If you do not want to select genes, you... discard this field.

**Comment by dridk** [comment]
already displayed in the toolbar
