### ISSUE TITLE
Create save to selection button

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#168]
A button to save the current query to a selection. 
This button correspond to the "CREATE" actions . 

Where to put this button ? 

- in variant_view ? ===> yes 
- In mainwindow ? ===> no

**Comment by ysard** [comment]
It **was** on variant_view. But it should be also in filters_editor:
When you modify a VQL query filters are updated and here you may want to save them.

Moreover the save button on filters_editor doesn't work (for now).
