### ISSUE TITLE
Create a standalone page 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#171]
Based on https://github.com/tailwindtoolbox/Landing-Page
I started to create a landing page quickly . 
![image](https://user-images.githubusercontent.com/1911063/95981490-01afb700-0e1f-11eb-9f98-672fe37a0412.png)

We should use the purple color theme made by @it-s  . I may ask him for help. 

The color shema is avaible here : 
https://github.com/labsquare/Poster/blob/master/JOBIM2019/poster2.svg

**Comment by dridk** [comment]
Good news ! Someone will help us to create this page ! 

Here is a new mokup I did :  

![image](https://user-images.githubusercontent.com/1911063/96046241-744a8200-0e73-11eb-88e7-8229ca2419cd.png)

**Comment by ysard** [comment]
Hum I prefer the first version; the second is more rigid and the color is less cheerful.
Psychology and first impressions are important for a landing page.
Moreover, nice graphics/histogram are not available anymore; it would be better to not show them.
