### ISSUE TITLE
VQL problems

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#174]
- [x] About SET and word sets

In the doc:

> IMPORT SET "gene.txt" AS boby

This will not work because we expect in the program the following syntax:

> IMPORT sets "gene.txt" AS boby

Error:

>  Traceback (most recent call last):
    File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/plugins/vql_editor/widgets.py", line 208, in run_vql
        command.create_command_from_obj(self.conn, cmd)()
    File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/core/command.py", line 370, in import_cmd
        raise vql.VQLSyntaxError(f"option {feature} doesn't exists")
    cutevariant.core.vql.VQLSyntaxError: ("option SET doesn't exists", None)

3 problems here:
- [x] UPPER CASE for "features" is not expected, this is also the case for `selections, fields, samples` features.
=> see `show_cmd, drop_cmd, import_cmd` in command.py
=> I think that you VQL parser should return the feature in lower or UPPER case; But we need to decide which one.

- [x] SET or sets or set names for features are confusing in comparison to set operations on selections.
=> I purpose to use WORDSET in order to have an explicit keyword here.
=> Idem for the `sets` table: wordsets will be a better name; and its the time to update it because it will change the DB structure.
Such a modification will be a pain later...

- [x] When used in a filter, it is the SET keyword that is purposed:
> SELECT chr,pos FROM variants WHERE gene IN SET["genelist"] 

=> can we homogenize these keywords ?

---

- [x] Do not forget to add the new VQL commands to vqleditor.py. Otherwise it will not fully support the VQL language.

---

Still about wordsets but more about filter editor this time:

- [x] The IN operator is unusable in general.
In the field, if you enter `("CICP23","CHID1" )` it will be transformed in a VQL query with `'("CICP23","CHID1" )'`.
=> See the quotes: the tuple is casted into a string. Thus the VQL parser raises an error.

- [x] The IN operator should just expect a list of coma separated words.
=> A normal user CAN'T have the IQ to understand the actual expected format of the input!

- [x] IN operator directly in VQL console, such a command:
> SELECT favorite,chr,pos,ref,alt FROM variants where gene in ("CHID1")
is not usable.
A tuple of 2 elements seems to be mandatory!
So this syntax works:
> SELECT favorite,chr,pos,ref,alt FROM variants where gene in ("", "CHID1")

- [x] IN SET operator directly in VQL console:
> SELECT favorite,chr,pos,ref,alt FROM variants WHERE gene IN SET['mygedne']

... is transformed in filter_editor into `IN ('SET', 'genelist)`.
This is not expected.

I guess that there is great amount of voodoo things here because `IN SET["genelist"]` is equal to `IN ('SET', 'genelist)`.
But currently the language seems to be very overloaded.
What is overloaded is hard to maintain.
And what is hard to maintain will not be maintained.

This is very important for the release. Such problems should be addressed...
Its more important than the filter plugin itself.

**Comment by ysard** [comment]
Tests are ok but not GUI and vice versa:

`IMPORT WORDSET "gene.txt" AS mygene`:
```
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/core/command.py", line 373, in import_cmd
    raise vql.VQLSyntaxError(f"option {feature} doesn't exists")
cutevariant.core.vql.VQLSyntaxError: ("option WORDSET doesn't exists", None)
```

Fixed to wordset but test crashes:
> accept_features = ("wordset",)

`sqlite3.OperationalError: no such table: wordsets`

I will fix that.

**Comment by ysard** [comment]
- [x] And doc is not updated with still "sets"...
- [x] Show command is not updated with and still use "sets"
- [x] VQL Doc of DROP clause is not updated

=> it's a partial update, not fixed at all...
=> Should be in a separated branch before first merge

EDIT: Sorry for the spam; but yes the confusion is legit. We always use plural form for SELECTIONS, FIELDS, SAMPLES etc. and now not for WORDSET;
I think we must follow the actual convention:

`IMPORT WORDSETS "gene.txt" AS mygene ` means import mygene in the existings WORDSETS.

But 
`SELECT chr,pos FROM variants WHERE gene IN WORDSET["genelist"] `
means use the unique WORDSET named genelist

**Comment by ysard** [comment]
Update about IN/NOT IN operators (see the problems above):

I tried to fix the problems of expected iterable for these operators.
I maid a crappy trick to convert comma separated values or tuples in string forms to Python Tuples:

https://github.com/ysard/cutevariant/blob/4c8ba91b35d578116085f490147f7a4a5a9f820c/cutevariant/gui/plugins/filters_editor/widgets.py#L169_L211

This works, but the quite ugly tinkering with Tuples that must contain almost 2 elements is not solved (see above).
I have some difficulties to understand this part of the program.
**In my opinion the grammar should expect tuples OR WORDSET function, after IN/NOT IN operators and parse them accordingly.**

Maybe the changes should be maid here:
https://github.com/ysard/cutevariant/blob/4c8ba91b35d578116085f490147f7a4a5a9f820c/cutevariant/core/querybuilder.py#L257-L262
... and the FilterField should be a kind of validator or just a StrField.

Currently the code does nothing and doesn't inspire me ><

Questions:
- Are you agree that FiltersFields widget should return typed data? This is the case now.
- Do you accept these changes for now? I'm ready to push big changes about filters plugin.

PS: I will extract all Fields Widgets from the plugin to put in in a separated file for now.
Maybe we should export them in `gui/widgets/` folder for easy reuse ?

-

**Comment by dridk** [comment]
After a long time of reflexion...... 

## Relation between VQL, Python and SQL  
First, I would share an illustration showing how VQL / PythonObject / SQL are related.. 
Actually, the code requires some refactoring to accord with the following shema. I will create an issue . 
     
![image](https://user-images.githubusercontent.com/1911063/97000127-965c9800-1536-11eb-95fe-d7c37d6d81c3.png)

## About filters 
For now, about filter, I propose to keep ONLY TWO representation of a filters . 
And use function to transform Python -> VQL and VQL -> Python.

- The VQL representation : 
        
             ... WHERE  var = 3 AND gene IN ("CFTR","GJB2") 

- The Python representation : 

           [
          {"name": "var", "operator": "=", "value": 3}
          {"name": "gene", "operator": "IN", "value": ('CFTR','GJB2')}
          ] 

So if we want a string representation of a value, we should keep the same than VQL syntax. 
the PythonToVQL of a tuple is done from querybuilder.filters_to_vql(). I can refactor it with a new function "value_to_vql".

- [ ] Create  a function  value_to_vql() to make it simple : 
    
         value_to_vql(3)   =>  "3" 
         value_to_vql("salut")  =>  " 'salut' " 
        value_to_vql(("CFTR","GJB2"))  =>  " ('CFTR', 'GJB2') "  
        value_to_vql(("WORDSET","boby") ) =>  "WORDSET['boby'] "

So, the filter editor should display the VQL representation. 
The field widget editor should edit the python object . 

### Filter editor with IN operator 
There is two kind of value with IN operator . The wordset tuple and the standard tuple.

- ('WORDSET', 'name')
- ('CFTR', 'GJB2') 

For now, I propose to keep only a string field as you suggest : 

- get_value will return value_to_vql(). For Wordset, il will be " WORDSET['boby']"
- set_value parse the string using a regular expression .

**Comment by ysard** [comment]
Ok thx for the examples, I understand the structure better, I review my work...

**Comment by ysard** [comment]
I understand why VQL => SQL needs a tuple `(WORDSET, 'name')` but not why SQL => VQL needs to display this tuple.

GUI: enter WORDSET['xxx'], VQL conversion : (WORDSET, 'xxx'), go back to GUI: It is not "to_vql() func" that is used but Python objects in filters dict, so it's (WORDSET, 'xxx') that is showed in the GUI...

**Comment by ysard** [comment]
WORDSET function is a pain to handle in filter field...
EDIT: its possible (we already do this for sample fields in VQL) but it's a pain...

We must show WORDSET['xxx'] but keep (WORDSET, 'xxx') internally.
Its a puzzle between UserRole and EditRole. Much overhead here.

Why not have used an operator complementary to the IN? "IN WORDSET" operator. 
Because this feature can only be used with IN if I'm not mistaken.

The syntax is also much cleaner.

**Comment by dridk** [comment]
that what I plan . Use "IN wordset" as Operator in editor.

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by ysard** [comment]
Workaround is here, quite clean, after a "night" of sleep.

It works for StrField and IterableField as a fallback. But it's ugly via a regex to make a cast from WORDSET["xx"] syntax to tuple syntax.

But yes in the future it will be much better to have a separated operator; for us and for users who will only have to enter the name of the wordset without worrying about heavy syntax.

- Commits are pushed in devel branch.
- I reduce the importance of the issue, it is no longer a blocking bug for the release.
