### ISSUE TITLE
Nice but cumbersome loading movie...

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#176]
![image](https://user-images.githubusercontent.com/14988285/96352476-af42f480-10c3-11eb-9f99-aee00dbb0ab5.png)
> Note: Yes, PyCharm can use up to 2,2Go to open some source files. Java is a beautiful language.
> I guess the future is to create IDEs in JS >< (spoiler: it's worse :+1: ).

And 90% of 1 CPU when it is in background (3,4Ghz CPU...)

- Yes it is designed to be displayed few seconds for each query;
- But when a filter is edited, this animations is still displayed as long as the filter is not correct;
- This app could be used in a mutualized computer; CPU resources are precious and this is not a vital feature.

I suggest to remove this, and just display a disabled table. All users can well understand such thing.

**Comment by klva** [comment]
Maybe just display a "Loading..." in the middle of the disabled table ?

**Comment by dridk** [comment]
Ok ! Lets add a simple text message with "Loading..." and make disable the table

**Comment by ysard** [comment]
I don't know why Qt is not efficient here. In a past project I partially fixed the problem by reducing a lot the size of the gif in pixels.
