### ISSUE TITLE
[CEP] (Cutevariant Enhancement Proposal): filters: how to save them?

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#178]
If we assume that the filters should be saved (I think they should be saved) because it is frustrating to have to redo a job every time you launch the soft), we have to decide how to do it.

And yes, it is a feature for the next release...

Several ideas with their pros and cons:

- Filters are stored in the project:
Integrate a new SQL table with either the whole query or a cleaner one:
the content of the filters dictionary of the State() object of Mainwindow.

    Pros:
    - Filters are limited to the project being processed.

    Cons:
    - No possibility of inter-project exchange
    - More SQL and I'm sick of it
    - One more potential VQL binding to code

- The filters are stored in the application settings (usual config file):

    For:
    - Accessible from all projects without action by the user
    - Easy and quick to implement

    Against:
    - Potentially useless filters for a particular project will pollute the interface.
    Note that it is possible that these cases will be rare...
    - Doesn't facilitate their exit from the program and thus the exchange on an online repository or whatever.
    - Filters will be editable only from the GUI, not with a simple text editor.
    - Develop a settings plugin to manage them

- The filters are exported to a user folder (depending on the OS) in a format
exchange type JSON.

    For:
    - Facilitates import and export
    - Facilitates sharing
    - Cutevariant can be supplied with a set of filters to accompany the filters plugin

    Against:
    - Potentially useless filters for a particular project will pollute the interface.
    Note that it is possible that these cases are rare...
    - Longer to develop (importer + exporter)
    - Develop a settings plugin to manage them

A mix of the last 2 could be also possible in order to reserve the JSON to an exchange format only.

**Comment by dridk** [comment]
What about storing the full vql somewhere? 
It will store the filters and the column .

**Comment by ysard** [comment]
Functionality added in 46c1329 + 35ead88:
- When a filter is saved, I mean the entire current VQL query.
- When a filter is loaded, I mean the filter part of a saved VQL query is loaded.

Saving VQL will allow us to do other things later with it.

- Save user filter in app settings
- Load predefined filters from filters.json embedded in filter plugin

It's quickly implemented but it works.

Export/Import of filters is not a priority for now.
I send this issue in the next milestone where its fate will be decided whether someone is hipped about it or not.

**Comment by dridk** [comment]
All are saved now with the config.py
