### ISSUE TITLE
variant_view: Not expected CPU consumption

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#179]
Maybe related to #176, but not sure.

There is still 8% of permanent CPU consumption due to this plugin.
I have turned off all the plugins and when this one is loaded the CPU usage is here.

My sql_runnable_merge has the problem, my dev branch hasn't.
So this is not normal.
My dev branch is a quite old but located juste before the addition of SqlRunnable related changes...

[edit] I tried to trace the calls of the functions but nothing to say. Responsible routines seem to be located in C++ libs of Qt.

**Comment by dridk** [comment]
Does it happen only when loading new variants ?

**Comment by ysard** [comment]
No I simulate fake data with no SQL query and no thread pool:
total = 0
variants = []

So a blank "interface" with just the buttons and a blank view still present the problem even with basic Formatter.

Paint events are known to be CPU consuming but we don't use them very much...

**Comment by dridk** [comment]
Seems there is a refresh somewhere... or a timer... 
Try to remove the setItemDelegate()...

**Comment by ysard** [comment]
Trouvé, petit coquin tu m'as laissé un QMovie caché dans VariantView...

https://github.com/labsquare/cutevariant/blob/69cbf27220991d8f0311345411cd8d3efb2895a3/cutevariant/gui/plugins/variant_view/widgets.py#L527-L530

Décidément cette méthode pour charger des Gifs est mauvaise et ce n'est pas un problème récent:
Déjà en 2002:
https://bugzilla.redhat.com/show_bug.cgi?id=61928
2010:
https://bugreports.qt.io/browse/QTBUG-2441

Je pense qu'il faut au moins appeler la méthode `stop()` plus tard. Ce n'est pas fait pour être exécuté en permanence...
