### ISSUE TITLE
detect genotype fields in VQL

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#18]
It would be greate to detect sample fields from parser : 

```
SELECT chr, pos, sample("sacha").gt  FROM all 
SELECT chr, pos FROM all WHERE  sample("sacha").gt == 1 AND sample("lucas").gt == 2

```
VQL Model must returns a samples set (unique) : 

      {'select': ('chr', 'pos', 'sample("sacha").gt '), 'from': 'all', samples: ("sacha", "lucas")}

**Comment by Aluriak** [comment]
I don't get it. You want a list of all things enclosed by `"` ?

What are you trying to achieve ?

**Comment by dridk** [comment]
I want a list of all things enclosed by samples("xxxxxx") . You can put those things into a "samples" set

**Comment by dridk** [comment]
I need to build a sql query with a join . For example , here is the SQL result from VQL result  :+1: 

3 tables: 
 - variants ( id, chr, pos )
- samples (id, name) 
- sample_has_variant ( sample_id,variant_id, gt ) 

VQL : 
`SELECT chr, pos, sample("sacha").gt, sample("lucas").gt FROM all   `

SQL : 
```sql
sacha_sql_id = "SELECT id FROM samples WHERE name = 'sacha' " 
lucas_sql_id = "SELECT id FROM samples WHERE name = 'lucas' " 

SELECT chr, pos, s1.gt , s2.gt FROM  variants
LEFT JOIN sample_has_variant s1 ON s1.variant_id = variants.id AND s1.sample_id = sacha_sql_id
LEFT JOIN sample_has_variant s2 ON s2.variant_id = variants.id AND s2.sample_id = lucas_sql_id
```

**Comment by dridk** [comment]
And It may be greate to have also well formated columns inside the model  . ( Not sure if it's relevant from DSL or Query object ) 

Actually  :  
`{'select': ('chr', 'pos', 'sample("sacha").gt '), 'from': 'all'}`

Suggestion : 
``{'select': ('chr', 'pos', 's1.gt', 'from': 'all', samples =[{"s1": "sacha"}]}``

**Comment by Aluriak** [comment]
I'm pretty sure this is a second order problem.

Why do you need 

    {'select': ('chr', 'pos', 's1.gt', 'from': 'all', samples =[{"s1": "sacha"}]}

and not a parsed tree ?

    {'select': ('chr', 'pos', {'type': 'sample', 'args': ('sacha',), 'sub': 'gt'}, 'from': 'all'}

What is the grammar of `sample` and `.gt` ? A controlled vocabulary ? Just letters ?

**Comment by dridk** [comment]
- "chr", "pos" and more  are fields from variant table 
- "gt" and more are fields from sample table 
- sample() should be a function like COUNT() in SQL . 
If you want to get "xx" fields from sample "lucas" : 

      SELECT sample("lucas").xx FROM variant WHERE sample("lucas").xx = 4

But you may be true. This is a second order problem . I can parse and extract sample fonction. Tell me what you want to do

**Comment by Aluriak** [comment]
I think i understand. Do you mean that these two are equivalent ?

    SELECT sample("lucas").xx FROM variant WHERE sample("lucas").xx = 4
    SELECT xx FROM lucas WHERE xx = 4

**Comment by dridk** [comment]
Absolutly not .... :) 
You have 2 kind of fields: 
Field per variant record 
Field per sample per variant 

    SELECT chr, pos, sample("lucas").gt, sample("sacha").gt FROM variants

See [snpfift filters](http://snpeff.sourceforge.net/SnpSift.html#filter)

So... you can parse as you said. The following output is good. But keep in mind that you can have this field in both select and where statements

    {'select': ('chr', 'pos', {'type': 'sample', 'args': ('sacha',), 'sub': 'gt'}, 'from': 'all'}

**Comment by ysard** [comment]
Is this issue can be closed now?
