### ISSUE TITLE
Github pages / documentation

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#187]
Didn't know if I have rights but sphinx doc is now updated (for the Core part).

I completely rewrote it all.
On the other hand, we should avoid pushing the content of `docs/build/` onto the repository's classic branches.

I saw a "hack" with a `git subtree` but I do not understand well the use of GitHub pages. I guess you have to send everything to a branch named gh-pages but maybe it has been disabled because there are already pending pages, and the site displays a 404 error.

https://labsquare.github.io/cutevariant

**Comment by dridk** [comment]
oui.. j'hésitais à utiliser github ou directement readthedocs. Mais on peut remettre la gh-pages

**Comment by ysard** [comment]
Via github ça oblige à suivre des fichiers générés; sur readthedocs la procédure d'envoi est plus simple (pas de "bidouilles" avec subtree) et on n'inclut pas le contenu de docs/build/html dans le dépôt ou dans une branche.
Je pense que les github pages sont plus adaptées à un site codé manuellement qu'à un site auto-généré.

**Comment by dridk** [comment]
Je propose qu'on utilise mkdocs , que je peux hébérgé si besoin ! 
Par ailleurs, je parlais avec le dev de qutebrowser sur telegram/pyside ! On peut s'inspirer grave ! 
https://qutebrowser.org/ 
https://github.com/qutebrowser/qutebrowser

**Comment by ysard** [comment]
> On peut s'inspirer grave ! 

Ouais je me disais qu'il manquait dans la doc une section donations ou demande d'emploi (pas recrutement hein) :p

Fais comme tu veux RTD est commun mais moi j'héberge mes docs sur des serveurs tiers.
De toute façon ça ne coûte rien en bande passante, il faut juste générer les pages html et les envoyer en ssh/rsync (plus rapide).
La logique voudrait que tu mettes ça sur labsquare.org, nouveau dossier "cutevariant" et pouf fait en 5 min.
