### ISSUE TITLE
About the naming/tagging of versions

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#188]
Problems here:
31388db
5ff56fe (dependent of the previous one)

> Pypi doesn't support beta naming...
> So .. The previous version was 0.1.15... The new release should be called 0.2 == MENDEL !

PyPi supports the PEPs.
Please read 386 and 440: https://www.python.org/dev/peps/pep-0440/, https://www.python.org/dev/peps/pep-0386/

TL;DR (because these peps are informative but long to read #confinement...):
Python packages generally adhere to the version format major.minor[.patch][sub].
- The major number is 0 for initial, experimental releases of software.
It is incremented for releases that represent major milestones in a package.
- The minor number is incremented when important new features are added to the package.
- The patch number increments when bug-fix releases are made.
- Additional trailing version information is sometimes used to indicate sub-releases.

Example of versioning:
0.0.1.dev0 (first commit), 0.0.1 (first release), 0.1.0 (first improvements), 1.0.0b1 (almost done), 1.0.0 (yes), 2.0.0 (broke the api)

From PEP:
>Strings like "a", "b", "c", "alpha", "beta", "candidate" and so on (that
>come before "final" alphabetically) are assumed to be pre-release versions,

---

So a "0.2" for Mendel means a stable release.
But:
- We aren't yet in 100% stable state
- It's a major milestone
- It's not just an addition of new features

The problem is not "beta", but "beta" followed by "dev".
You can choose "b" instead of beta if you want but in all cases zest.releaser helps you here:

> Enter version [1.0.0.beta0]: <type enter if you doesn't want to change it, or 1.0.0.beta1>
> INFO: Set __version__ in cutevariant/__init__.py to '1.0.0.beta1'
> INFO: Changed version from 1.0.0.beta0 to 1.0.0.beta1
> ...
> Check out the tag (for tweaks or pypi/distutils server upload) (Y/n) Y
> INFO: Doing a checkout...
> ...
> Writing cutevariant-1.0.0b1/setup.cfg                                          # Yes it renames the package to b1
> ...
> Upload to pypi (Y/n)? n
> Upload to pypitest (Y/n)? Y
> ...
> Enter new development version ('.dev0' will be appended) [1.0.0.beta2]:
> ...
>  __all__ = ["core", "gui"]
> -__version__ = "1.0.0.beta1"
> +__version__ = "1.0.0.beta2.dev0"
> OK to commit this (Y/n)

During this last step you have to choose what you want to do:
- Accept the commit and let it use 1.0.0.beta2.dev0 which is an error for pypi until you rename it to 
1.0.0.beta2 during the next release...
- .. or refuse the commit which allows you to have a cleaner list of tags during dev.

Ex:
https://test.pypi.org/project/cutevariant/1.0.0b1/

**Comment by dridk** [comment]
Ok ! 
The problem was that 1.0.0b1 was before the 0.1.16 in version ordering . So 0.1.16 was the most recent version.  I was not able to install cutevariant with pip.
So, lets keep 0.2... until a stable version called 1.0.0.   Is it okay for you ?

**Comment by ysard** [comment]
Bizarre:
```
>>> from pkg_resources import parse_version
>>> parse_version("1.0.0b1") < parse_version("0.1.16")
False
>>> parse_version("1.0.0b1") > parse_version("0.1.16")
True
```

Ok let's continue to fix the current version before adding more unstable thing. This for a few days.
