### ISSUE TITLE
Replace travis / AppVeyor by github-ci

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#189]
using github-cli will be helpful. Avoiding to have different CI service .

**Comment by ysard** [comment]
We're mature enough to run the tests ourselves before we push on the devel/master branches and know what breaks and why we leave it broken.
It's still useless unless it's launched on another OS than the ones we use to run the tests. And still, not with every batch of commits...
Why not on a special branch named CI tests where we can push on demand and see the status when we want to know it.

If it's just for the CI badge tests coverage i can add a cute static SVG...

This travis file contains only a few lines and is proportionally one of the most modified files in the repository. 
Be careful not to waste time with these technos they are made for this purpose. 
Contrary to what most of people think they add layers of complexity. This has always served to unbalance the provider/client relationship in the dev world in favor of the provider.

**Comment by dridk** [comment]
I guess we can run CI using a keyword in the commit.

**Comment by dridk** [comment]
we are using github-CI now ! Which is quite better than travis ! 

It is avaible here : https://github.com/labsquare/cutevariant/actions/

It works for both mac / windows / linux . 
But default, only Linux VM are used to run test when pushing or pull_requesting on devel and master branches. 
If you want to run test on windows and MacOS , and deploy some binary avaible as "artifact", you must add "[deploy]" keyword inside your commit .
