### ISSUE TITLE
VQL improvement

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#190]
Some possible improvement: 

Look over this projects to get inspired:

 [gemini](https://gemini.readthedocs.io/en/latest/content/querying.html)  / [SnpSift](https://pcingola.github.io/SnpEff/ss_introduction/)  / [variant tools](https://vatlab.github.io/vat-docs/) /   [SILVAR](https://github.com/brentp/slivar#family-expressions) / [VCF PRocessor ](http://lysine.univ-brest.fr/vcfprocessor/filters.html)
- [ ]  Use HET/HOM_REF/HOM_ALT key values
``` ..WHERE sample("boby") = HET```

- Flag expression 
``` 
Where flag is True
Where flag = 1 # work actually
Where flag exist 
 ``` 
- [ ]  None expression 
``` Where impact is NULL ```

- [ ]  multiple  values #182
 ```( CI95[0] > 0.1 ) AND (CI95[1] <= 0.3)```
same for genotype: 
```sample("boby").pl[0]```

- [ ]  New regular expr operator
prefere =~ and !~  which is more standard 

- [ ]  Allow arithmetic operation 
``` ... WHERE pos + 3  = 19999 ```
``` ... WHERE score1 + score2 > 10 ```

- [ ]  Allow *\** as sample name : 
``` WHERE sample("mum").DP > 7 AND sample("father").DP > 7 ```
should be rewrite as : 
``` WHERE sample(*).DP > 7 AND sample(*).DP > 7 ```

**Comment by SteampunkIslande** [comment]
I agree with them all except maybe for the flag expressions: having multiple ways of expressing the same thing can be confusing.
Other than that I like the other ideas, they are a perfect fit for a good old hackathon !

**Comment by dridk** [comment]
move to discussion
