### ISSUE TITLE
Add Save project button

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#192]
It would be greate to work on a copy of the sqlite project named "mydb.db.current" .
And save the current project when clicking on "Save Project" button. 

- mydb.db~    =>  mydb.db when saving. 

This can be a problem for large dataset... 
Track all sql write query and apply them when saving,  is another solution . But don't know if it possible.

**Comment by ysard** [comment]
The soft is not designed for that.
I will not advise to go into the complex and time-consuming implementation of transactions here, nor into multi-user usage patterns.

What are the features that write in BDD?
- favorites
- comments
- ACMG classification
- selections (after filtering, after importing BED file)

When you take an action you can delete it immediately, nothing is irreversible and data can be reversed in a glimpse.

Conversely, when you have worked for a while, sorting / classifying the data, you will bite your fingers if the project is not saved in the event of a computer crash or loss of access to the virtual machine...

At most we can add a button that resets the project (clears the selections, etc.)

**Comment by dridk** [comment]
Cutevariant has now "save session" and "restore session"  which save the state of all plugins .
