### ISSUE TITLE
Export variant table to excel

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#197]
All in the title.

**Comment by ysard** [comment]
Question: The goal is precisely that users do not use this kind of unsuitable tools, introducing errors in the processing of data, right?

Also: For the moment the CSV export is for the data currently viewed in variant_view (All pages, except data from other tables); 

In fact you want to keep this behavior and add another export option, or patch the current behavior to query the table and not the view ?

**Comment by dridk** [comment]
Ah .. I didn't know we already have this feature :D  !
