### ISSUE TITLE
QueryPluginWidget ideas

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#21]
VariantListPlugins are widget which get the current variant query ( list of variant ) . 
Here are some ideas : 

- [x] BarChart for SNPs

- [ ] Barchart for SNP, insertions, deletions, others

- [x] Transition / Transversion 
Display content of transition and transversion as a pie chart. 
http://dridk.me/images/post17/chart.jpg
http://dridk.me/transition_transversion.html

- [x] Hpo plugin 
Display hpo terms as a tree . When you select a term it will update filter with genes belong to the term. The code is already avaible and need some improvement

**Comment by ysard** [comment]
Can you describe in details what do you want here please ?

**Comment by ysard** [comment]
Code has been removed in devel.
Deprecated issue. I close.
