### ISSUE TITLE
[CEP] Trio analysis plugin - pedigree

### ISSUE THREAD

**Issue by tetedange13** [labsquare/cutevariant#211]
The trio analysis plugin works fine, but possible ways of improvement:

- [ ] It seems that the pedigree given at import is **not taken into account**
=>It should pre-set 'roles' (father, mother, index) associated with each sample

- [ ] In the case where no pedigree was given at import, maybe create a .tfam once the user set 'role' of each sample + ran analysis 
=> Like that, no need to re-attribute role each time we want to run a different trio analysis

- [ ] Maybe add a sort of **correspondance between sampleID and 'roles'** based on the .tfam file
=> Like that, VQL queries become clearer, like:
`WHERE sample['father'].gt=0 AND sample['mother'].gt=0 AND sample['child'].gt=1`
(or should be in a specific issue, because related to the whole interface?)

**Comment by dridk** [comment]
https://github.com/labsquare/cutevariant/discussions/540
