### ISSUE TITLE
[CEP] Manage auto-refresh of columns

### ISSUE THREAD

**Issue by tetedange13** [labsquare/cutevariant#212]
As each GUI click to add/remove a column automatically reload variants_view, with a big VCF it can be painful to add several column after another.

Since release of v0.2.5 a "Refresh" button was added, but variant_view is still refreshed on GUI click on a column
=> Maybe add new parameter, to switch on/off auto-refresh 
=> User will have to click on "Refresh" once he selected all columns he wants

**Comment by dridk** [comment]
Fixed in last released
