### ISSUE TITLE
[CEP] Chose starting columns via import wizard

### ISSUE THREAD

**Issue by tetedange13** [labsquare/cutevariant#213]
Could be interesting to **chose directly starting/favorite list of columns through the "import wizard"**
=> Like this, user can skip the 1st step of adding several columns *via* GUI/VQL, before starting its VCF mining

**Comment by dridk** [comment]
May be better to have a predefined columns which can be saved and load for later

**Comment by dridk** [comment]
Cutevariant now supports "presets" from fields selector
