### ISSUE TITLE
VEP annotation has %3D caracter  in hgvs fields

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#220]
Benjamin Cogne : 
je suis en train de tester cutevariant sur du génome / VCF annotés et pré-filtrés.
J'aurais 2 petits soucis:
- au chargement des VCF il semble que le "=" sous format %3D tel qu'utilisé dans le champs HGVSp de VEP ne soit pas supporté / j'ai une erreur d'encodage ascii. Cela fonctionne lorsque je remplace le caractère

**Comment by benjamin-cogne** [comment]
hello,
le "=" est réservé comme délimitateur de champs, donc il est remplacé par %3D lorsqu'il correspond à une valeur par exemple dans le champs HGVSp par VEP, les variants synonymes sont encodés p.Asn17%3d pour p.Asn17=
Liste des caractères spéciaux dans VCF v4.3 à prendre en compte (https://samtools.github.io/hts-specs/VCFv4.3.pdf):
"""
The character encoding of VCF files is UTF-8.  UTF-8 is a multi-byte character encoding that is a strict supersetof 7-bit ASCII and has the property that none of the bytes in any multi-byte characters are 7-bit ASCII bytes.  Asa result,  most software that processes VCF files does not have to be aware of the possible presence of multi-byteUTF-8 characters.  Note that non-printable characters U+0000–U+0008, U+000B–U+000C, U+000E–U+001F aredisallowed.  Line separators must be CR+LF or LF and they are allowed only as line separators at end of line.  Somecharacters have a special meaning when they appear (such as field delimiters ‘;’ in INFO or ‘:’ FORMAT fields),and for any other meaning they must be represented with the capitalized percent encoding:
%3A:(colon)
%3B;(semicolon)
%3D=(equal sign)
%25%(percent sign)
%2C,(comma)
%0D CR
%0A LF
%09 TAB"""
