### ISSUE TITLE
create variant writer 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#232]
-  [x] export to bed
-  [x] export to vcf
-  [x] export to csv

**Comment by SteampunkIslande** [comment]
With [this commit](https://github.com/labsquare/cutevariant/commit/835d6a2479c54b2f285788264fd8dbe20d440adf):
- CsvWriter works as expected, and takes proper advantage of inheriting the new AbstractWriter class
- AbstractWriter provides connection to database, with only one query function (so far) to retrieve all variants.
- VcfWriter is not implemented yet. Looks like, even from [the doc itself](https://pyvcf.readthedocs.io/en/latest/_modules/vcf/parser.html#Writer), the _write_header method is not fully implemented yet
- PedWriter still works, but doesn't use the AbstractWriter as it should (still passes tests though...)

**Comment by dridk** [comment]
Cool !!

**Comment by SteampunkIslande** [comment]
Sorry, I forgot to mention this issue in my latest commit... Here is [the commit](https://github.com/labsquare/cutevariant/commit/25feadab749f3fa55a719712ef7a69190afac751)
