### ISSUE TITLE
New fields synax

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#237]
Actually, it is really hard to make distinction between fields from variants table or annotations table. 
I suggest to replace the fields selection : 

## Before 

```python
fields = ["chr", "pos", "gene", "impact", ("sample","boby","gt")]
```

By a dictionnary : 

## After 

```python

fields = {
"chr",
"pos"
"annotations": ["gene","impact"],
"samples": [{"boby": "gt"}]

} 

```

**Comment by SteampunkIslande** [comment]
Now in the latest release !
