### ISSUE TITLE
Regex filter inconsistency and error

### ISSUE THREAD

**Issue by SteampunkIslande** [labsquare/cutevariant#238]
There is an inconsistency when defining regular expressions, between Filters editor plugin and VQL editor.

If you go to Filters editor and create a condition with REGEXP, then hit apply, everything works fine and the VQL editor gets updated with the regular expression. However, if you run a query with the exact same VQL expression, the filters editor plugin ends up with a 'equal' sign instead of REGEXP. It also gives a key error, '$regexp' not found in condition_to_sql.

**Expected behavior**
When writing a regular expression in VQL, expecting REGEXP operator in the filters editor

**Comment by dridk** [comment]
VQL use ~ operator for regular expression . 
I suggest to harmonize the naming.  
Could you replace "REGEXP" to "~" from filter editor  ?

**Comment by SteampunkIslande** [comment]
Actually filter_editor retrieves the name of the operators in a dict called OPERATORS_PY_SQL, and not OPERATORS_PY_VQL...
So what about renaming the dict as well ?
