### ISSUE TITLE
Selections creation enhancement

### ISSUE THREAD

**Issue by SteampunkIslande** [labsquare/cutevariant#240]
Right now, the user can create a selection with spaces. And VQL doesn't like that at all. 

So there are three possible fixes:
1- Make it impossible for the user to enter any white space character when creating/changing the name of the selection.
2- Automatically replace any white space with underscore (after user input)
3- Make it possible, in VQL, to support spaces.

Last solution is the worst I guess, because first it implies some dangerous refactoring of vql.tx and vql.py (although doesn't sound too bad IMHO), but also because there is no real point in having spaces in a selection name. And if you really need several words to describe your selection, having underscores instead of spaces is really not that bad.

**Comment by dridk** [comment]
@SteampunkIslande Did you fix this issue ?
