### ISSUE TITLE
Cutevariant ameliorations

### ISSUE THREAD

**Issue by SteampunkIslande** [labsquare/cutevariant#262]
- [ ] Make the table empty upon query error
- [x] Make the table empty upon database open failure (for now it is just a status bar message, hard to see)
- [ ] Ajouter un ordre des fields (déplacement dans le tableau ?) dans les paramétrages de fields editor
- [ ] Ajouter un "order by" (multiple) dans le paramétrage des fields
- [x] Make the variant count per page customizable
- [ ] Weird line count. In the example file, there are 510 045 variants, however 1 379 373 lines are shown.

**Comment by dridk** [comment]
Could you create one issue per feature ?
