### ISSUE TITLE
Simple ameliorations

### ISSUE THREAD

**Issue by SteampunkIslande** [labsquare/cutevariant#263]
- [x] Being able to batch edit 'favorite' and 'classification' fields
- [x] Being able to click the 'favorite' icon instead of using context menu
- [x] Being able to select variants only from one sample (or a list of samples), quickly and without complex query
- [x] Make the 'comment' column editable inside the variant view

**Comment by SteampunkIslande** [comment]
IMHO, selecting only from one sample is already as simple as checking the sample's genotype field in the fields editor...

**Comment by bioinfo-chru-strasbourg** [comment]
In that way, you see the genotype of this samle, but you do not select variants (het and hom) only present for this sample.
It's more something like "SELECT fields WHERE [filters] AND sample.gt != WT"

**Comment by SteampunkIslande** [comment]
Batch edit classification was implemented as mentioned in #264

**Comment by SteampunkIslande** [comment]
>  Being able to click the 'favorite' icon instead of using context menu

@dridk I'm not sure, but I think this is trickier than it looks like, since the icon is part of the cutestyle, which means it will only be a cell with 0 or 1 if no style is applied.

So what about a tool button at the top of the view ?

**Comment by antonylebechec** [comment]
> > Being able to click the 'favorite' icon instead of using context menu
> 
> @dridk I'm not sure, but I think this is trickier than it looks like, since the icon is part of the cutestyle, which means it will only be a cell with 0 or 1 if no style is applied.
> 
> So what about a tool button at the top of the view ?

Basically, I think it's tricky too. But I don't really know the underlying technical constraints. If a button could be a simple way to speed up the feature, it's great!

Actually, I suggest a global rebuild of this feature, by expending this favorite feature as a "validation classification" feature (like "pathogenic classification") : 
- "Favorite" field as integer, maybe renamed (or another field if easier)
- Fixed values (0=Unclassified, 1=Favorite, -1=Rejected/or something for noise mainly) and more flexible ones (2 and more, user defined if needed)
- quick buttons for 1=Favorite and -1=Rejected, and 0=Unclassified (as exemple)
- Bash classification, using contextual menu, and a quick button/list

This feature can be a plugin, but I think it will deeply improve CuteVariant. Especially if it is combined with a sutainable validation database feature (plugin currently in dev in own team), all annotation will be cross assigned between projects (to automatically remove technical noise already classified, quickly identify already "favorite" and "pathogenic" variants)...

**Comment by SteampunkIslande** [comment]
I see, maybe I'll go for a simple button for now, and let's see. Is it too risky also to assign a tag to the whole selection (not just the first 50 that are visible, but every line the request retrieved ?)

Also concerning the 'tag' feature, with more than two values that favorite has for now, I think it's more like a new feature, however the goal for now is making the features we already have work at their best. I really like the idea though, and I would be excited to develop it after the next official release !

**Comment by antonylebechec** [comment]
Yes, let's do it simple for the moment, a button. Why is it to risky to to assign to the selected variant? It's what you did with "pathogenic classification", isn't it? I think it's not really interesting to assign avery line the request retrieved.
Let's develop another feature as a plugin and/or in the next release.

**Comment by SteampunkIslande** [comment]
Here's a glimpse of how the actions look like now in the variant view
![cutevariant variant view actions 1](https://user-images.githubusercontent.com/64743278/124194137-5045d400-dac8-11eb-9378-07d39202e039.gif)

**Comment by antonylebechec** [comment]
Great! And you can tag as Favorite all selected variants as well?

**Comment by SteampunkIslande** [comment]
Yes, you can !

**Comment by SteampunkIslande** [comment]
And now, we can select all variants of a sample by double clicking it in the genotype view
See screen cast below
![voila](https://user-images.githubusercontent.com/64743278/124195817-74ef7b00-dacb-11eb-9d81-30ededec0e30.gif)

**Comment by antonylebechec** [comment]
> Yes, you can !

Perfect!

**Comment by antonylebechec** [comment]
> And now, we can select all variants of a sample by double clicking it in the genotype view
> See screen cast below
> ![voila](https://user-images.githubusercontent.com/64743278/124195817-74ef7b00-dacb-11eb-9d81-30ededec0e30.gif)

Double Perfect!
