### ISSUE TITLE
Make possible batch to tag Favorite and Classification with a selection of variants

### ISSUE THREAD

**Issue by bioinfo-chru-strasbourg** [labsquare/cutevariant#264]
As it's possible to tag as Favorite and to classify a uniq variant, it would be great to tag and classify a selection of variants.
This will accelerate noise tagging (see #265)

**Comment by SteampunkIslande** [comment]
Here is a screen cast of the new batch classification in action
![Cutevariant batch classification](https://user-images.githubusercontent.com/64743278/123627514-6591d880-d812-11eb-96db-b9e9e4a390f6.gif)

**Comment by dridk** [comment]
extremely slow to edit multiple variant ! Optimization required !

**Comment by SteampunkIslande** [comment]
Fixed in #263
