### ISSUE TITLE
When creating a project, make it possible to choose indexed fields

### ISSUE THREAD

**Issue by SteampunkIslande** [labsquare/cutevariant#267]
In the project wizard, at the 'select fields' page, add a checkable column with indexed fields

**Comment by SteampunkIslande** [comment]
![image](https://user-images.githubusercontent.com/64743278/124610928-3c57f480-de71-11eb-8baf-b12f39e592c9.png)

**Comment by SteampunkIslande** [comment]
I didn't make a screencast since there is nothing interesting going on visually after the user click.
But how faster it gets when querying, that's impressive

**Comment by dridk** [comment]
Not sure if it is actually relevant since we use in app indexation
