### ISSUE TITLE
When creating a project, tag variant as uncertain classification, and make it possible to choose default classification

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#268]
Currently, the default classification of a variant is "3=Variant of uncertain significance".
This is confusing, because the user never applied any classification.
I suggest to tag variants as "0=Unclassified" by default, and make possible to choose the classification when a project is created.

**Comment by antonylebechec** [comment]
Moreover, I suggest to add a "noise" or "exclude" classification, with negative value (-1).
Another feature would be to let user define their own classification, notwithstanding the fixed ACMG classification (1-5) and unclassified (0)

**Comment by dridk** [comment]
ok ! should be easy to fix !

**Comment by antonylebechec** [comment]
Juste notice that we would consider "0=Unclassified" as noise until the "-1=noise" is available.
So in own case, these 2 suggestions should be done simultaneously

**Comment by antonylebechec** [comment]
> ok ! should be easy to fix !

Cool!
