### ISSUE TITLE
Generalisation of fields for all samples 

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#269]
Add a selection of fields from "FORMAT" and show columns for all sample.
As an example, by choosing "GT" and "DP" will show columns for sample.[*].gt and  sample.[*].dp.
In the same way, it could be great to use this generalisation for filter (e.g. sample.[*].dp>30).

**Comment by dridk** [comment]
yes, that's a good idea ! 

By the way, we have count_var count_hom, count_het like snpEff ! 
For instance : 
```
SELECT chr, pos FROM variants where count_var = 1 
```
will select all variant present in only one sample among all samples.

**Comment by antonylebechec** [comment]
Another idea should be to add in the "Genotype View" these samples' fields (DP, AD, VAF...), after "Phenotype". This seems to be more a "Samples View", but it will help a lot to evaluate the quality of the variant (DP, AD, VAF...). Perhaps it's technically easyier to developpe
