### ISSUE TITLE
Groupby (chr,pos,ref,alt) 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#27]
It must be possible to group variant  by (chr,pos,ref,alt) in the variantviewer. 
This is often the case when you have many transcript annotation per variant

**Comment by ysard** [comment]
Is this a duplication of #31 ?

**Comment by dridk** [comment]
not really. This feature required SQL manipulation. 
#31 is about contextMenu .

**Comment by ysard** [comment]
This feature seems to be implemented now.
