### ISSUE TITLE
[variant_view] Copy cell value

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#277]
- [x] [ variant_view] : From the context menu, add "copy value" action from the current cell
- [x] [ Settings ] : Make reset works ! Use config.reset() 
- [x] [ Field Editor] : Qd on met l'index, on voit pas que ca souligne 
- [x] [Help] : Developper > Create Plugins ....

**Comment by SteampunkIslande** [comment]
Resetting needs some more work with individual setting pages.
For now, only global resetting and external links (variant view) resetting works
