### ISSUE TITLE
Tags behavior issue

### ISSUE THREAD

**Issue by bioinfo-chru-strasbourg** [labsquare/cutevariant#279]
When selecting "tags" for variant(s), these tags are replacing existing tags. This behavior could remove tags to keep, but without knowing it.
Propositions:
1/ "add" selected tags, instead of replacing them. Another option could remove all tags.
2/ an option "Replace" or "Add" or "Remove" instead of "Apply".
3/ distinction between tags on a uniq variant (list of checked tags for this variant, and list is "replaced") and a list of variants (empty list of tags, and they are "added". Or list of checked tags in gray to identify tags already used)

**Comment by dridk** [comment]
ok ! 
The tag widget will have current tag checked.
