### ISSUE TITLE
Add "bin" columns in variants table 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#28]
According to this post : http://plindenbaum.blogspot.com/2010/05/binning-genome.html
we should add a "bin" columns in variants table to improve SQL query performance 

I did the C++ code , it's avaible here : 
https://github.com/labsquare/CuteVariant-cpp/blob/devel/src/cutevariantcore/variant.cpp#L198 

Also avaible here : 
https://github.com/vatlab/VariantTools/blob/407c0db49860b2c9bd14a985f02ec0a10c071bfa/src/ucsc/lib/binRange.c

**Comment by ysard** [comment]
Ok I see, the most frequently requested data is encoded in binary in a number.
This is probably of interest at the scale of a large database. For the moment, this is early optimization and SQL is not currently a weak point of the program :o
