### ISSUE TITLE
Tags update error

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#280]
When update multiple variants with multiple tags (with or without tags) :

Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/plugins/variant_view/widgets.py", line 1332, in update_tags
    update_tags = set(tags + current_tags)
TypeError: can only concatenate list (not "str") to list

As example (update tag "noise")

![image](https://user-images.githubusercontent.com/40463532/126311009-1f544053-63d5-4cae-aad6-4e4ca3b45fd9.png)

**Comment by antonylebechec** [comment]
Another example (update/add tags with "noise") on this selection :

Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/plugins/variant_view/widgets.py", line 1332, in update_tags
    update_tags = set(tags + current_tags)
TypeError: can only concatenate list (not "str") to list




![image](https://user-images.githubusercontent.com/40463532/126311568-4f212ae8-3f6a-44e8-b211-777b7eea5b32.png)

**Comment by dridk** [comment]
@antonylebechec let me know if it works now !

**Comment by antonylebechec** [comment]
It works!

**Comment by antonylebechec** [comment]
A "remove" button is needed now...
(remove also tags not in the configured list)

**Comment by antonylebechec** [comment]
Add "bruit", then "noise", then "rendre"!!! great!

![image](https://user-images.githubusercontent.com/40463532/126390165-a86a2d27-9de1-4e5d-bf3b-3b807f0d8ebb.png)

![image](https://user-images.githubusercontent.com/40463532/126390195-5f21b7a6-50af-4469-bf0b-36364a86e545.png)

![image](https://user-images.githubusercontent.com/40463532/126390229-6835cd69-e57f-4dd5-9e67-f5d0b1bd474c.png)

![image](https://user-images.githubusercontent.com/40463532/126390264-898d6799-d74b-4bc6-afa0-be61baee03fd.png)
