### ISSUE TITLE
Unable to install and run cutevariant from source

### ISSUE THREAD

**Issue by fierytortilla** [labsquare/cutevariant#289]
**Description**
I am having trouble running the cutevariant program via the installation commands provided in the "From Source" section in README.MD. I have tried running these commands several times now and consistently get the same error messages. I am currently running these commands in the terminal of my Mac OSX 10.14. 

**To Reproduce**
Steps to reproduce the behavior, I run these commands as is from the "From Source" section, but with the additional command to `cd` into the cutevariant directory.
1. `git clone https://github.com/labsquare/cutevariant.git`
2. `cd cutevariant`
3. `make install_deps`
4. `make run` 

Rather than getting the cutevariant app up and running, instead I get the following error:

`python -c "import configparser; c = configparser.ConfigParser(); c.read('setup.cfg'); print('\n'.join([i for i in (c['options']['install_requires'] + c['options.extras_require']['dev']).split('\n') if i and 'PySide2' not in i]), end='')" | xargs -0 -d "\n" -I {} pip install '{}'
xargs: illegal option -- d
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
make: *** [install_deps] Error 1`

Interestingly, if I run the command `python -m cutevariant` after cloning it from github, the program does run, however, I would prefer to get it running purely using the source at this time.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14
 - Version of Cutevariant: 0.3.6.

**Comment by dridk** [comment]
Hi, 

Could you test using the following documentation ? 
https://cutevariant.labsquare.org/developer/install-for-dev/

**Comment by dridk** [comment]
I fixed the documentation . Please tell me if it works for you.

**Comment by fierytortilla** [comment]
@dridk I tried implementing your steps and I get the following error when I run `python -m pip install -e`:
    `e option requires 1 argument`

Furthermore, when I run `python -m cutevariant`, I get the error:
    `ModuleNotFoundError: No module named 'cachetools'`.

**Comment by dridk** [comment]
sorry for that !  
The "." was missing from the documentation. It is : 

```bash
pip install -e . 
```

And cachetools has not been installed from setup.cfg : 

```bash
pip install cachetools
```

I fixed everything. It should works.Tell me if it is okay for now !

**Comment by fierytortilla** [comment]
@dridk Thanks so much, it works perfect now!
