### ISSUE TITLE
Search bar for ColumnsQueryWidget 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#30]
ColumnsQueryWidget must have a toolbar and a search bar to filter model data. 
You can use QSortFilterProxyModel to do that. 

I suggest to keep the searchbar on the bottom and invisible. Display it only when it is triggered by the user ( button or shortcut CTRL+F)

**Comment by ysard** [comment]
Also, in order to facilitate the search, columns should be sorted in alphabetical order.
