### ISSUE TITLE
Handling concurrency issues when multiple users on the same project

### ISSUE THREAD

**Issue by SamuelNicaise** [labsquare/cutevariant#303]
We want multiple users to be able to read and write in the same cutevariant project at the same time.  Projects are available on a shared network drive. It works, but we are worried about concurrency issues, as biologists will sometimes work on the same variants on different samples at the same time. If a value was changed by user2 after user1's last refresh, user1 will write over user2's modifications without warning. 

This concerns the 4 writable fields: favorite, comment, classification, tags. 

We suggest for example that on every writing action, cutevariant checks if the displayed value and current database value are equal. Ideally, if the values are different, a "conflict resolution" interface could show up, allowing the user to pick which value to keep.

**Comment by dridk** [comment]
Interesting read about this : 

https://sqlite.org/forum/info/e4dd574a6a5d0d29
