### ISSUE TITLE
Classification on more than selected variants

### ISSUE THREAD

**Issue by bioinfo-chru-strasbourg** [labsquare/cutevariant#306]
Please edit this template:

**Describe the bug**
Classification ACMG on more variants than selected on

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Select one or more variant
2. Click on 'Classification' and select a classification
3. Check classified variant

Note:
This example show variants in genes that are possibly overlapping

**Expected behavior**
Only selected variants should be classified

**Screenshots**
<img width="753" alt="Capture d’écran 2021-11-08 à 17 05 41" src="https://user-images.githubusercontent.com/40687400/140776423-c0f60ef0-ede6-4b1f-9204-56357b2b841f.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version of Cutevariant: from the GUI (Help/About Cutevariant) on devel branch.

**Additional context**

**Comment by bioinfo-chru-strasbourg** [comment]
**Additionnal context**
Selected variant are in the same chr:pos:alt:ref
Only NM change
Is classification can be specific to a uniq NM ?

**Comment by dridk** [comment]
No,  I don't think so .  Classification is related to variant , not annotation.
