### ISSUE TITLE
CORS issues with IGV plugin

### ISSUE THREAD

**Issue by SamuelNicaise** [labsquare/cutevariant#315]
When trying to load a different genome than hg38 (we use hg19), the IGV plugin fails to load and sends back an error message.

js: Access to XMLHttpRequest at 'https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta.fai' from origin 'https://igv.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
js: Error accessing resource: https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta.fai Status: 0

**To Reproduce**
Steps to reproduce the behavior, for example:
1. In the IGV plugin, click on Genome > Human (GRCH37/hg19)
2. See error

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Version of Cutevariant: latest devel commit (db829dd)

**Additional context**
I noticed there already is _self.settings().setAttribute(QWebEngineSettings.LocalContentCanAccessRemoteUrls, True)_ in the code, but it doesn't seem to work.

**Comment by SamuelNicaise** [comment]
More additional context:
- https://igv.org/app/ works perfectly from the browser on the same computer
- we have a local instance of the IGV browser that uses hg19 by default. I tried using its url instead, but this leads to the same CORS error when the instance tries to initialize

--> so it's apparently not an issue with the corporate proxy?

I also attempted to use .json files containing a path to local genomes instead, but ends up with a "Not allowed to load local resource" error. There's no issue to load bam/bed/vcf files, but I can't load a .json genome or session.

**Comment by dridk** [comment]
Does Json load works from https://igv.org/app/  ?

**Comment by SamuelNicaise** [comment]
Loading a JSON apparently does not work on https://igv.org/app/ either (or I can't find how to do it correctly). I will make a ticket on their side.

However, the CORS error message is specific to cutevariant.

**Comment by antonylebechec** [comment]
Are there some setting to switch off CORS authenfication?
Such as:
https://doc.qt.io/qtforpython/PySide6/QtWebSockets/QWebSocketCorsAuthenticator.html?highlight=cors#PySide6.QtWebSockets.PySide6.QtWebSockets.QWebSocketCorsAuthenticator

**Comment by antonylebechec** [comment]
Here is the log output on Mac:
"no opengl support set"
