### ISSUE TITLE
MacOS interface

### ISSUE THREAD

**Issue by bioinfo-chru-strasbourg** [labsquare/cutevariant#318]
Please edit this template:

**Describe the bug**
Problems with MacOS interface:
- When plugins are in tabs, impossible to "detached" plugins.
- Visualization "strange" for first variant column.

**To Reproduce**
Steps to reproduce the main behavior (plugin in tabs) :
1. Drag and drop 2 plugins to merge them in tabs
2. Drag and drop 1 plugin tab to "detached" it
3. Impossible to detach

**Expected behavior**
Plugin detached

**Screenshots**
![image](https://user-images.githubusercontent.com/40687400/145802703-9d2bd216-e2db-4df3-9e70-7148e0dc32f6.png)
![image](https://user-images.githubusercontent.com/40687400/145802772-ae0f03ed-e107-4e83-82ff-d167517ff324.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version of Cutevariant: devel

**Additional context**

**Comment by SamuelNicaise** [comment]
I have the same behavior on Windows. I use the "detach" button in those cases. I don't know if this is the expected behavior

![image](https://user-images.githubusercontent.com/19996531/145804323-b74cb22b-9a32-4a69-bc73-c23f6e136e03.png)

**Comment by bioinfo-chru-strasbourg** [comment]
I got it!
Thanks @SamuelNicaise!

**Comment by bioinfo-chru-strasbourg** [comment]
Problem solved!
