### ISSUE TITLE
VQL model_from_string: expected behaviour ?

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#34]
`model_from_string()` can return such a structure:
`MODEL: {'select': ('chr', 'pos', 'ref', 'alt'), 'from': 'all'}`

Later in `Query.from_vql()` (file `core/query.py`), `model_from_string()` is used and we expect that the attribute `self.columns` is a list, not a tuple.

I do not know what is best: if this function must return a structure with one or the other type but it must be documented because later (on `Query.items()`) a concatenation is made between `self.columns` and a list, and it throws an exception in the current state of things.

**Comment by Aluriak** [comment]
Whatabout just casting toward what you need ?
If you need a list for internal reasons, you should rebuild your own in any case (don't let your code be knocked-out by objects received from elsewhere).

The obvious fix is quite simple : cast in list [here](https://github.com/labsquare/cutevariant/blob/master/cutevariant/core/query.py#L201).

Now, we can also say that `model_from_string` must use list for the select clause. Would be a change from tuple to list [here](https://github.com/labsquare/cutevariant/blob/master/cutevariant/core/vql.py#L135).

**Comment by dridk** [comment]
I agree with @Aluriak. Vql parser should returns a tuple . We can parse it as a list or something else from the  Query class.

**Comment by ysard** [comment]
Ok so the API must return a tuple, I'll add this to the doc of this function...
