### ISSUE TITLE
[snpeff annotation] feature_id missing

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#340]
Field "feature_id" is missing when annotation is provided by snpEff!

It seems to be in the code:
File cutevariante/core/reader/annotationparser.py line 53:
```
"feature_id": {
        "name": "transcript",
        "category": "annotations",
        "description": "Transcript name",
        "type": "str",
    },
```
but I did not have the column in the table...
The info is in the VCF file

**Comment by dridk** [comment]
"feature_id" columns is renamed to "transcript". I did this to have same name with VEP annotation.

**Comment by antonylebechec** [comment]
Sure. But I don't see it, neither as "transcript" nor "feature_id".
My test, when I change "name" of "transcript_id" in annotationparser.py line 54:
- "name" = "transcript": NO field
- "name" = "feature_id": field present
- "name" ="bidule": field present

**Comment by antonylebechec** [comment]
Suggestion:
remove check "ann.field" existing in "field" (INFO) in file annotationparser.py line 274:
```
            # if _f["name"] in self.variant_field_names:
            #     # This field is already in variants fields
            #     # => do not use it!
            #     # Append None in place of the name of the field
            #     # with the aim to not break handle_annotations() when it splits
            #     # the annotation field.
            #     self.annotation_field_name.append(None)
            #     LOGGER.info(
            #         "handle_descriptions: '%s' field also found in variants; skipped",
            #         _f["name"],
            #     )
            #     continue

```
