### ISSUE TITLE
[Filters view] Bug with $any $all

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#346]
Using "samples.*.gt" in "Filters view", an error appears:

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/40463532/158064407-1a2e60ed-869e-41f9-bb1e-3e019945139c.png">

By clicking on "Run" in "VQL editor", this error disappears, and "Filters view" fields changed ("*" to "$any"):
<img width="1787" alt="image" src="https://user-images.githubusercontent.com/40463532/158064473-956a8b31-f867-411e-8c49-8120b269ce77.png">

There is a need to homogenize "*/$any" and "?/$all"

**Comment by dridk** [comment]
This
