### ISSUE TITLE
[validation] some bugs and improvements

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#373]
Some bugs and improvements:

- [x] Contextual menu fail when no "chr" field in query (#362)
```
Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/plugins/validation/widgets.py", line 626, in contextMenuEvent
    self.current_variant["chr"]
KeyError: 'chr'
```

- [x] Ficon is not defined
```
Traceback (most recent call last):
  File "/Users/lebechea/BIOINFO/git/cutevariant/cutevariant/gui/plugins/validation/widgets.py", line 187, in data
    return QIcon(Ficon(0xF139A)).toPixmap(20, 20)
NameError: name 'Ficon' is not defined
```

- [x] Ensure icons are clearly defined
   - icons for Lock/Unlock/Rejected sample
   - icon's colors related to validation on variant

- [x] Ensure than validation is locked for locked samples and no genotype variant

- [x] List of columns not selected and not visible and not checkable (MacOs)
<img width="338" alt="image" src="https://user-images.githubusercontent.com/40463532/162792695-728ecc0f-64b8-4ca6-8bd1-3fa5618e5143.png">

- [x] Select fields to display close to presets, at the right

- [x] Add quick selection of samples/genotype in the main window (only on "sample_has_variant" values?)
As example :
   - selection of samples with the selected variant associated to specific **genotypes** (to help user to quickly list samples with genotype)
      <img width="347" alt="image" src="https://user-images.githubusercontent.com/40463532/162795193-6ba504b9-c9da-4380-a8df-21f58758d084.png">

   - selection of samples with the selected variant **validated** (to help user to quickly list samples with validation)
      <img width="403" alt="image" src="https://user-images.githubusercontent.com/40463532/162795366-fde2c823-b960-431f-9150-13b4c86fec19.png">

   - selection of samples with the selected variant **tagged** with a specific tag (to help user to quickly list tagged validation)
      <img width="327" alt="image" src="https://user-images.githubusercontent.com/40463532/162795425-25b65e0f-a0fd-46e5-902f-1ba1e4c8ba55.png">

- [x] Contextual menu > variant validation not locked when no genotype for a variant
<img width="481" alt="image" src="https://user-images.githubusercontent.com/40463532/162793453-344388c0-2895-4ba2-b247-feb3a251aa66.png">

- [x] Search samples with pattern
<img width="376" alt="image" src="https://user-images.githubusercontent.com/40463532/162795854-4d4e0476-d97f-4c87-8bd7-9d879569f32b.png"> <img width="376" alt="image" src="https://user-images.githubusercontent.com/40463532/162795881-ca0baa88-879d-402b-b8f4-0b47cef5d068.png">

- [x] Selection with a list of samples (separated by space or comma, allow both, especially to be able to copy/paste from a spreadsheet)

- [x] Selection with a SampleSheet (Illumina format)

- [x] Selection with tags on samples that are not preset (e.g. added during import)

- [x] Search list with icons (and text?)
<img width="356" alt="image" src="https://user-images.githubusercontent.com/40463532/162796014-aed3df8e-f988-40d6-a3db-4b7f6336581c.png">

- [x] Columns in list of samples more usable
   - [ ] Order by on columns
   - [ ] Selection of columns (or all columns), such as sex, father, mother, hpo, others...
   <img width="443" alt="image" src="https://user-images.githubusercontent.com/40463532/162796620-a5dcf6d7-b3d6-47f5-ac74-d19a4db6f25f.png">

- [x] button "Add to selection" and "remove selection(s)" and "clear all" more visible
<img width="443" alt="image" src="https://user-images.githubusercontent.com/40463532/162796703-dbe1ed43-df38-4073-8e15-f25b7d06433f.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/40463532/162796838-e6deca7e-b1a0-4d42-a9f5-6f87d10c78e2.png">

- [x] Columns in selected samples
<img width="447" alt="image" src="https://user-images.githubusercontent.com/40463532/162796947-2d88c309-4b8f-42e4-931f-d58322a1551b.png">

- [x] Contextual menu to open Edit each samples (either in "All samples" and "X Selected sample(s)" tabs)

- [x] List of selected samples at the bottom of the window (after the samples' table and before "Cancel" / "OK" button), for each tabs. The list will be just a non editable text field, with samples separated by a space or comma, with a limitation (no more X samples shown, user can list all of them with details in the "X Selected sample(s)" tab)
 
- [x] Double click to add samples (one by one)

- [x] Facilitate source creation and selection (PR 395)

- [x] Validation of multiple sample_has_variant at the time (issue #395)

**Comment by dridk** [comment]
- add all samples button  (select all )
- Add validation source button

**Comment by SamuelNicaise** [comment]
> Ensure than validation is locked for locked samples and no genotype variant

should be avoided in case a biologist wants to validate a variant that was undetected by callers

**Comment by antonylebechec** [comment]
Most of items are solved
