### ISSUE TITLE
bed module

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#38]
Create a bed module to make possible to intersect variant within bed region

**Comment by Aluriak** [comment]
We should make room for the bed module, and ensure to call `sleep()` once in a while for efficiency.

**Comment by dridk** [comment]
And you may want to add picture in your room using the pillow library

**Comment by ysard** [comment]
We need bed files in examples to start implementing this feature :p

**Comment by dridk** [comment]
in sql.py , we need the following function : 

```
def create_selection_from_bed(selection, name, bed_file):
          """ Create a variant selection which intersect the bed file 
          
           selection : Source table : @SELECT ... FROM selection
           name : new selection name
           bed_file : bed file path
          """  
          # Create temporary sql table (bed) with : chr, start, end field
          # Intersect query with temporary table ( SELECT .. from ... Where chr=bed.chr AND start > bed.start AND end < bed.end and create a new selection named "name"
           

```

**Comment by dridk** [comment]
A bed file is just a text file with chromosom, start and end position : 

```
chr1  213941196  213942363
chr1  213942363  213943530
chr1  213943530  213944697
chr2  158364697  158365864
chr2  158365864  158367031
chr3  127477031  127478198
chr3  127478198  127479365
chr3  127479365  127480532
chr3  127480532  127481699
```

**Comment by ysard** [comment]
Can you think about the gui part of this implementation? A wizard to add bed files on batch?
It could purpose a zone to add files with a button or with drag and drop, to a dynamic list widget.
The wizard should also allow users to rename their selection based on each bed file.
Once the wizard is validated by the user, selections are created.

**Comment by ysard** [comment]
Can you think about the gui part of this implementation? A wizard to add bed files on batch?
It could purpose a zone to add files with a button or with drag and drop, to a dynamic list widget.
The wizard should also allow users to rename their selection based on each bed file.
Once the wizard is validated by the user, selections are created.

**Comment by ysard** [comment]
We have to handle specific BED coordinates:
https://daler.github.io/pybedtools/intervals.html#bed-is-0-based-others-are-1-based

>  BED files are 0-based (the first base of the chromosome is considered position 0) and the feature does not include the stop position.
>  GFF, GTF, and VCF files are 1-based (the first base of the chromosome is considered position 1) and the feature includes the stop position.

Should we let the user choose the format of his file in the wizard (in case a BED file is coded in 1-based)?
Errors at this level could have very serious consequences...

**Comment by ysard** [comment]
Support of BED files is here on cdc518f.

How to use:
```
from cutevariant.core.reader.bedreader import parse_bed_file
sql.create_selection_from_bed(self.query.conn, name, parse_bed_file("coucou.bed"))
```

**Comment by dridk** [comment]
We should use the same coordinate format for the whole application. 0-based seems more logic.

**Comment by dridk** [comment]
It seems you are using pybedtools which depend on bedtools binary. I am not sure this will works for windows and mac

**Comment by ysard** [comment]
Yes,

pros:
- avoid to develop a hand-made parser
- support of bedgraphs and simple bed files and any other file formats with unconstant headers...

cons:
- doesn't support space separated columns in files (>< WHY ? WTF!)
despite the fact it is implicitly supported in the [norm](https://www.ensembl.org/info/website/upload/bed.html).
- 11 Mo just for a parser (we don't use any other feature of this lib)
- Install on Windows is not supported (firstly because of pysam dependence).

Like the vast majority of tools in bioinformatics we must rewrite the wheel or put hands on it event if it not our work.
Well... I should develop a hand made parser...
-_-'

**Comment by ysard** [comment]
And like many tools in bioinfo it is a fucking black box that does everything and especially what we do not need.
I just need a multi-platform file parser for bed files and I end up with 11MB of sources, including C++ to be compiled, libs to make venn diagrams, set operations, annotation etc.

Why not have done an independent project for the parser? WTF ????

Do you know/recommend another simple Python parser for bed files?

**Comment by dridk** [comment]
About the GUI implementation : 
- From selection panel , a button : "create selection from bed " should be suffisant . 
- From VQL , something like this ? 
   
     "CREATE boby FROM variant INSIDE boby.bed

**Comment by dridk** [comment]
I think the default csv parser is quite enough. Bed file is a csv file at
the end.

**Comment by ysard** [comment]
Maybe just 
`CREATE xxx FROM FILE file.bed`

An inserted BED file should always refer to `variants` table; so "FROM variants" is a permanent option.
Set operations are made by a user once the BED is added as a standalone selection.

PS: with Postgresql we have:
https://www.postgresql.org/docs/9.0/sql-copy.html

`COPY table_name FROM 'path/to/data.csv'` => insert file in DB
and:
`COPY table_name TO 'path/to/data.csv'` => export DB to file

**Comment by ysard** [comment]
Ok, i just pushed a standalone BED parser (not like pybedtools) for gz files, text files and strings (like pybedtools); with a support for tabs and spaces delimited columns (not like pybedtools).

The parser is covered by tests.

See effb1b2
