### ISSUE TITLE
Automatic formatting using black and pre-commit

### ISSUE THREAD

**Issue by Aluriak** [labsquare/cutevariant#4]
In order to get a properly formatted code (because [it would be much welcome](https://github.com/labsquare/CuteVariant-python/pull/3/commits/937d1bc51d74636a3da4bfa0b66335293b815b7e)), a good way would be to use [black](https://www.mattlayman.com/blog/2018/python-code-black/).

Instead of relying only on hand-crafted black PR just like #3, it would be useful to setup [pre-commit](https://pre-commit.com/), to get [black automatically fired at commit time](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8).

**Comment by ysard** [comment]
Seems to be solved via git hook.
