### ISSUE TITLE
[tags] Change tag name in config does not change tag name in DB

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#402]
**Describe the bug**
Change tag name in config does not change tag name in DB.

**Expected behavior**
When a tag name is changed, all tags in DB change.

**Desktop (please complete the following information):**
 - OS: Wondows10
 - Version of Cutevariant: distribution on HUS/Strasbourg.

**Comment by dridk** [comment]
Humm.. Bon, je pense qu'il va falloir mettre les tags en base pour cette feature.

**Comment by antonylebechec** [comment]
Ça serait mieux pour contrôler les tags en effet.
Mais ça suppose que les tags ne sont plus dans config alors ? Donc spécifique d'un projet ? 
Ou alors on trouve un truc pour synchroniser le tout...

**Comment by dridk** [comment]
Pour la release, les tags sont écrite à la main dans un champs dédié .
On mettra de l'autocompletion depuis le fichier de config.
