### ISSUE TITLE
[Validation] Not refresh when new project/DB

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#407]
Please edit this template:

**Describe the bug**
When a new project/DB is created or loaded, list of samples in Validation widget is not refreshed.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create/Open a project/DB
2. Select Samples in Validation widget
3. Create/Open a NEW project/DB
4. See that sample list is still the same

**Expected behavior**
List of samples cleared in Validation widget when create/open a new project/DB.

**Screenshots**
![new_project_same_sample_in_validation_widget](https://user-images.githubusercontent.com/40463532/165132076-84ae8db5-fa15-45e2-8e9a-5c77391ca5b6.gif)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version of Cutevariant: devel

**Comment by dridk** [comment]
Fix with https://github.com/labsquare/cutevariant/commit/75d6bf9922cc1cc7af8c94c612e5f3aa0d5d4217
