### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#43]
Dev doc is needed for at least all functions of this project...

We have to know in a wink by which function a function is called and when.
For now we have at least 53 Objects without docstrings and a huge amount of functions without them. This is a problem when it comes to maintaining the project now, and it will be even more in weeks.
Assuming that a class docstring corresponds to the complete documentation of this class, here is the list of objectives to achieve:

$ prospector | grep "cutevariant/\|Line\|Missing docstring"

- [ ] cutevariant/gui/filterquerywidget.py
    pep257: D107 / Missing docstring in __init__
    pep257: D107 / Missing docstring in __init__
    pep257: D107 / Missing docstring in __init__
    pep257: D107 / Missing docstring in __init__
- [ ] cutevariant/gui/hpoquerywidget.py
    pep257: D107 / Missing docstring in __init__
    pep257: D105 / Missing docstring in magic method
    pep257: D107 / Missing docstring in __init__
    pep257: D107 / Missing docstring in __init__
- [ ] cutevariant/gui/omnibar.py
    pep257: D107 / Missing docstring in __init__
- [x] cutevariant/gui/viewquerywidget.py
    pep257: D107 / Missing docstring in __init__
    pep257: D107 / Missing docstring in __init__

**Comment by Aluriak** [comment]
You may want to use [doctest](https://docs.python.org/3.5/library/doctest.html).

**Comment by ysard** [comment]
Please, for the moment do not touch/do modifications in sql.py. Many changes to do before in this file...

**Comment by ysard** [comment]
Tips from pep257:
D204 / 1 blank line required after class docstring (found 2)
D200 / One-line docstring should fit on one line with quotes (found 3)
D205 / 1 blank line required between summary line and description (found 0)
D212 / Multi-line docstring summary should start at the first line
D404 / First word of the docstring should not be `This`
D403 / First word of the first line should be properly capitalized ('This', not 'this')

There are currently 246 warnings on the project. I can't fix them all...
This issue is still up to date...

**Comment by ysard** [comment]
25 files were documented over 29.
Still 4 missing. I left only these.
filterquerywidget.py is not implemented and viewquerywidget.py still suffers from a big lack of doc.

**Comment by ysard** [comment]
Not evolving since 1 year and a half.
![img](https://media.tenor.com/images/b7795b796da4711ce70de48c18cdec6e/tenor.gif)
