### ISSUE TITLE
Classification des variants depuis la variant_view

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#438]
Dans le menu contextuel du variant : 

-Rajouter un menu "Samples" avec tous les samples présent dans get_state("samples") 
- Pour chaque sample, rajouter un menu avec la classification du samples 
- Qd on clique sur cette classification , appeler une fonction on_sample_classification  qui va : 
- Ecrire la nouvelle classification du samples avec sql.update_samples 
- Rafraichir le plugin samples avec :   if "samples" in mainwindow.plugins alors mainwindow.refresh_plugin("samples")

menu > samples > sample1 > classication 1

**Comment by antonylebechec** [comment]
Fait dans la branch "add_validation_on_variant_table"
