### ISSUE TITLE
Fix order by 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#452]
Use join in querybuilder with orderby

**Comment by dridk** [comment]
Comment fixer ce bug ( un truc de ce genre ) 

Ajouter le parametre order_by et fixer le test
- https://github.com/labsquare/cutevariant/blob/49991dcf6905e17846e7359f164c148ed6a88f2f/cutevariant/core/querybuilder.py#L110  

Ajouter le parametre order_by et fixer le test
- https://github.com/labsquare/cutevariant/blob/49991dcf6905e17846e7359f164c148ed6a88f2f/cutevariant/core/querybuilder.py#L134

Supprimmer 
- https://github.com/labsquare/cutevariant/blob/49991dcf6905e17846e7359f164c148ed6a88f2f/cutevariant/core/querybuilder.py#L743

**Comment by antonylebechec** [comment]
Some fails in VQL editor:
```
FAIL: SELECT favorite,classification,chr,pos FROM variants ORDER BY samples['HORIZON'].gt ASC
PASS: favorite,classification,chr,pos FROM variants ORDER BY ann.gene ASC
PASS: favorite,classification,chr,pos FROM variants ORDER BY alt ASC
```
Du to Function not str?
