### ISSUE TITLE
Crash when clicking on selection item

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#47]
- Import test.snpeff.vcf 
- Create a query : SELECT chr, pos FROM all WHERE ref = T 
- Save the query as sel_T
- Create a query : SELECT chr, pos FROM all WHERE ref = C
- Save the query as sel_C
- Type a new query : SELECT chr,pos FROM sel_T   It works 

Select the first item from the selectionQueryWidget ... It crashs the application

**Comment by ysard** [comment]
The slot "changed" is not implemented, i commented it.

**Comment by ysard** [comment]
It appears that this is not a problem of signal connected to another signal.
QueryRouter.widgetChanged() is well called but it leads to an infinite loop of calls to it, followed by the emission of the signal changed() by SelectionQueryWidget(). Other widget are also participating to this mess.
Maybe we should stop signal propagation in one way or another?
Maybe with a self._silence = True like in columnquerywidget ?
