### ISSUE TITLE
selections table and its association table

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#49]
The association table selection_has_variant only stores tuples of (variant_id, selection_id).
But since there are multiple versions of variants displayed, this table has a lot of duplicates.

I'm implementing a unique constraint on this, but it depends on queries with the DISTINCT keyword in create_selection_from_sql():
SELECT DISTINCT variants.rowid, {selection_id} ...

Is this OK ?

Also: Foreign keys on SQLite is a mess...
I read [here](https://www.sqlite.org/rowidtable.html) that applications applications should not normally access the rowid directly, but instead use an INTEGER PRIMARY KEY.
We use rowids everywhere.
This hidden id of sqlite is not persistent and might change, therefore its use is forbidden/not possible in foreign keys, because a change might brake all relations between tables.

I'm digging in this; problems are coming...

**Comment by dridk** [comment]
Yes you can change it . Since I group variant now, they must not be any duplicate. But I would like to keep the option of non grouping. 
About the rowid, ok, let's do some change and create an ID field every where.  What about creating the table WITHOUT rowid ?

**Comment by ysard** [comment]
Replaced by #50
