### ISSUE TITLE
VQL: default FROM clause

### ISSUE THREAD

**Issue by Aluriak** [labsquare/cutevariant#5]
In most examples, the FROM clause is `variants`. Since it sounds like the very basic usage, what about making FROM clause optional, with `variants` as the default value ?

Would be a change in VQL parser only.

**Comment by dridk** [comment]
Because I switch terms from 'variants' to 'all' recently. I didnt update
the code with the new change.


Le mar. 15 janv. 2019 à 12:25, Lucas Bourneuf <notifications@github.com> a
écrit :

**Comment by Aluriak** [comment]
Does not change the main idea. What about it ?

**Comment by Aluriak** [comment]
\><

**Comment by dridk** [comment]
As you suggest , the minimal query should be : 
        
       SELECT chr,pos,ref,alt   

I closed the issue because I thought this is confusing . However after further consideration, It looks like a good idea.

**Comment by ysard** [comment]
Maybe it's time to look at this with the new version of grammar. 
In the absence of FROM xxx: do not raise this kind of error:
`ERROR: TextXSyntaxError: Expected '(' or ',' or 'FROM' at position (1, 24) => 's, ref, alt * where ref'., Col: 24`

The FROM variants clause will always be added anyway by query.sql() or query.sql_count()
