### ISSUE TITLE
[variant view] Error in first field

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#508]
First field not in the variant table

Example "chr":
![image](https://user-images.githubusercontent.com/40463532/173162878-3955d784-f74d-4845-a245-ed4b9007520f.png)

**Comment by dridk** [comment]
Cannot reproduce this bug

**Comment by antonylebechec** [comment]
Difference between command line:

python3 -m cutevariant 

![image](https://user-images.githubusercontent.com/40463532/173189737-e4bbff59-26ad-4f48-9196-3e3120d56041.png)

python3 -m cutevariant -v notset

![image](https://user-images.githubusercontent.com/40463532/173189755-b60d3eec-775e-48a1-b478-0705fa458e41.png)

Moreover, 2 messages:
```
qt.qpa.fonts: Populating font family aliases took 285 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x600000dafbd0 'Search'
```

**Comment by antonylebechec** [comment]
Test with verbose option:
-v notset: BUG
-v info: BUG
-v error: BUG
-v debug: OK
No bug without option

**Comment by dridk** [comment]
incredible ...

**Comment by dridk** [comment]
Git bisect give me commit : ea1da7de087669bc4b86e590176dda5bd4322b43

**Comment by antonylebechec** [comment]
a side effect?

**Comment by dridk** [comment]
It was a missing... Long time ago, "id" columns was show/hide depending on debug mode .
