### ISSUE TITLE
Errors on insertions - what can i do

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#52]
# Old SQLite
## INSERT OR IGNORE
- mask other errors than violation of unicity => bad
- return the lastrowid of the latest correct query (not the id of the dup variant => problematic)

## INSERT OR REPLACE
- not dedicated to violation of unicity but try to overwrite the current variant
- do a deletion AND an insertion
- Change the lastrowid of the current variant => big mess in the database for all rows that used the old id

# New SQLite:
## ON CONFLICT ... DO NOTHING
- specific to the violation of unicity
- lastrowid is still not the correct one

## ON CONFLICT ... DO UPDATE SET
- specific to the violation of unicity
- lastrowid is still not the correct one (this is different from REPLACE because there isn't a new row in the DB)

---

Since we cannot continue with this error, can we go to the next variant, without inserting annotations/samples (that can be informative) of this problematic one?

If yes: ok problem solved.
If no: we would better to:
- raise an error with a standard INSERT INTO for old SQLite, catch it and ...
- use ON CONFLICT ... DO NOTHING for new SQLite, use cursor.rowcount to know how many rows are modified, and if 0...

... query the variant_id according to the problematic primary key, then follow insertions with this id.

what am I implementing?

**Comment by dridk** [comment]
yes ! annotation and sample are relative to variant . If variant is wrong, annotation and sample too.
