### ISSUE TITLE
validate reader output using shema

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#53]
From abstractReader, create checks methods (check_fields, check_variant) for get_fields and get_variant, using shema library .
@see #45

**Comment by dridk** [comment]
import is now really  slow with large file.... Need an option to disable check methods

**Comment by ysard** [comment]
Yes, maybe we could assume that the file is good and thus, not slow down insertions for users with correct files.
Also, if an error is generated at the end of the process, the process can be redone with further checks.
I speak essentially about primary keys/unicity constraints during insertions which are still slowing down data processing and are easy to detect.

Also, types of fields are checked at least by the vcf parser used.
Ex: Put a text data in a field dedicated to a position of a variant: there will be an error.

More generally, about #45, the aim is to build files with this kind of errors, and see what we can do to handle them.
If it is very expensive in terms of insertion time, it will be necessary to think of a system of fallback as described above;

**Comment by dridk** [comment]
schema is now used only for unit test
