### ISSUE TITLE
[Sources] Selected source in bold/white not visible on Bright style

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#549]
Selected source is not visible in Bright style (white/bold)

![image](https://user-images.githubusercontent.com/40463532/175811862-7260e6a0-0099-4d13-8964-ec60a2a11596.png)

**Comment by dridk** [comment]
C'est corrigé ca ? ca marche chez moi

**Comment by antonylebechec** [comment]
C'est corrigé avec le PR d'aujourd'hui (un autre PR a du planté, j'avais déjà corrigé)
