### ISSUE TITLE
[crash] Crash on exe - on open CuteVariant

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#552]
Please edit this template:

**Describe the bug**
CuteVariant crash on open

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Open CuteVariant

Note:
- not reproductible

**Expected behavior**
Not crash

**Screenshots**
<img width="976" alt="image" src="https://user-images.githubusercontent.com/40463532/175928457-148dafbd-edd9-423a-90de-09fb7e5e7b25.png">

**Desktop (please complete the following information):**
 - OS: Windows (exe)
 - Version of Cutevariant: devel

**Comment by dridk** [comment]
@SamuelNicaise Peux tu verifier que c'est fixé ?

**Comment by antonylebechec** [comment]
Pas facile à tester, pas trop reproductible. Mais on verra à l'usage surtout
