### ISSUE TITLE
[Crash] Crash on exe - on change project

### ISSUE THREAD

**Issue by antonylebechec** [labsquare/cutevariant#553]
Please edit this template:

**Describe the bug**
CuteVariant crash on project change

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change project

Note:
- Not reproductible

**Expected behavior**
Not crash

**Screenshots**
<img width="976" alt="image" src="https://user-images.githubusercontent.com/40463532/175928860-43afdd5a-1217-435f-baba-7c8d5f20076f.png">

**Desktop (please complete the following information):**
 - OS: Windows (exe)
 - Version of Cutevariant: devel

**Comment by dridk** [comment]
Pareil .. a tester..
