### ISSUE TITLE
Samples color is not updated when changing source in the main window selector

### ISSUE THREAD

**Issue by SamuelNicaise** [labsquare/cutevariant#557]
**To Reproduce**
Steps to reproduce the behavior, for example:
1. Open the Samples plugin
2. Add any number of samples
3. Double click on a sample. It will be highlighted as expected.
4. In the main window, change source from "current_samples" to "variants". 
5. The sample that is not selected anymore is still highlighted!

Expected behavior: highlighted sample is not highlighted anymore.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of Cutevariant: devel ; commit d7b673be5c918c0b32a59d777ffc6724fe55bb7d

**Comment by SamuelNicaise** [comment]
This issue only exists in bright mode. Behavior is as expected with dark mode.

**Comment by SamuelNicaise** [comment]
New addendum: switching from bright to dark then bright theme seems to have fixed the issue... I will check how it behaves on a "new user" install

**Comment by dridk** [comment]
cannot reproduce . Please open the issue if it is still there
