### ISSUE TITLE
Main window's Filters selector is not updated properly when creating new filters

### ISSUE THREAD

**Issue by SamuelNicaise** [labsquare/cutevariant#558]
**To Reproduce**
1. Open the Filters plugin
2. Save a new filter "filter1"
3. Click on the Filters list in the main window selector: "filter1" does not appear
4. Create a new filter "filter2"
5.  Click on the Filters list in the main window selector: "filter1" appears now, but "filter2" does not

--> some kind of off-by-one error?

The filters are still saved properly and will be available in the selector after closing and re-opening cutevariant. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of Cutevariant: devel ; commit d7b673be5c918c0b32a59d777ffc6724fe55bb7d

**Comment by antonylebechec** [comment]
Is click on "clear cache" refresh correctly?

**Comment by dridk** [comment]
click on refresh .

**Comment by antonylebechec** [comment]
Will be reopened if necessary
