### ISSUE TITLE
VQF for finding private variants

### ISSUE THREAD

**Issue by splaisan** [labsquare/cutevariant#572]
Salut Sacha et collègues,

I have a multi VCF file made of 18 unrelated samples and for each one I want to find candidate private variants (not necessarily somatic but different between samples and fully called) with a query inspired from the great SnpSift:

`isVariant('boby') AND count_var=1`

can you please help me find the right way to write **isVariant()** ? should I use something like:

`sample["boby"].gt != 0`. (is this OK of >0 is correct ? what are the operators for strings?)

I would prefer working without a pedigree unless this is the only way to do it because I will need as many pseudo-pedigree as I have samples (and need to import them each time?).

Also, how wan I count/exclude no-calls (./.) samples using VQF?
* an additional summary variable '**count_called**' would be nice to have

Thanks in advance

**Comment by dridk** [comment]
hi, 

'gt' field can be : 
* -1  for  ./.
*  0 for 0/0
* 1  for 1/0
* 2 for 1/1 


so you can do :

samples['boby'].gt > 0 to get all variant. 


You also have several counter. You may want to use count_var to exclude non call variant. 

Let me know if it works

**Comment by splaisan** [comment]
looks good, thanks
I can probably make use of 'clauses' to make this more incremental and easier to manage

Your tool is very inspiring, I wonder how difficult it is to build such a GUI to wrap some python CLI code, this could be quite useful to share data with colleagues who cannot use linux or python themselves.

**Comment by dridk** [comment]
you speak french, right? 

I did some video about qt for python 
https://m.youtube.com/watch?v=TnZECPVS2EM

**Comment by splaisan** [comment]
oui, expat Français en Belgique.
Merci pour le lien
