### ISSUE TITLE
regression in viewquerywidget

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#64]
The red rectangle with the number of variants is not displayed anymore.
Numerous exceptions raised:
```
Traceback (most recent call last):
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/viewquerywidget.py", line 370, in paint
    painter.drawText(option.rect, alignement, index.data())
TypeError: 'PySide2.QtGui.QPainter.drawText' called with wrong argument types:
  PySide2.QtGui.QPainter.drawText(PySide2.QtCore.QRect, PySide2.QtCore.Qt.Alignment, int)
```

=> Probably a type problem. Can you document this function please :p

**Comment by ysard** [comment]
Other issue:
This function paint() is called many many times: every time the window get the focus.
Is it efficient ?

**Comment by dridk** [comment]
Yes, the paint() event is called many time ; But it's decided by Qt .

**Comment by ysard** [comment]
What about the additional column with "0" before all sub variants now ?
