### ISSUE TITLE
VQL error due to quotes/simple quotes wrapping text

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#68]
sqlite3.OperationalError: near "G": syntax error

Currently:
- In the gui, only text without quotes is supported, BUT when the VQL query is refreshed after an action from the user, quotes are added and the query is no longer functional.

What we expect:
We have to choose a uniformly used syntax or support all syntaxes;
(Note: Text without quotes is confusing)

Can someone fix this error please, it's been there for months?

**Comment by Aluriak** [comment]
Can you provide examples of strings/query that are touched by this problem ?

I will modify the grammar to handle both writing (with quotes necessary when there is spaces in the string)

**Comment by ysard** [comment]
There probably are many bugs stacked but for now:

OK in the GUI:
`SELECT chr,pos,ref,alt FROM all WHERE ref = G`

A filter named "ref = G" appears on the left widget.
Now when you select/deselect a column in the widget "columns", the query is updated with the next syntax in this report (which is not functional if you write it by hand).

---

NOT ok in the GUI:
SELECT chr,pos,ref,alt FROM all WHERE ref = 'G'

With stacktrace:
```
Traceback (most recent call last):
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/querydispatcher.py", line 63, in update_all_widgets
    widget.on_change_query()
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/viewquerywidget.py", line 484, in on_change_query
    self.model.load()
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/gui/viewquerywidget.py", line 231, in load
    self.total = self.query.count()
  File "/media/DATA/Projets/cutevariant/cutevariant/cutevariant/core/query.py", line 360, in count
    f"SELECT COUNT(*) as count FROM ({self.sql()})"
sqlite3.OperationalError: near "G": syntax error
```
With the following query in the logs:
`SELECT variants.id,chr,pos,ref,alt,COUNT(variants.id) as 'childs' FROM variants LEFT JOIN annotations ON annotations.variant_id = variants.id WHERE ref=''G'' GROUP BY chr,pos,ref,alt`

---

NOT ok in the GUI:
`SELECT chr,pos,ref,alt FROM all WHERE ref = "G"`

With no stacktrace but with the following query in logs:
`SELECT variants.id,chr,pos,ref,alt,COUNT(variants.id) as 'childs' FROM variants LEFT JOIN annotations ON annotations.variant_id = variants.id WHERE ref='"G"' GROUP BY chr,pos,ref,alt`

---

Also, is it possible to support lower AND uppercase for SQL operators ?

**Comment by ysard** [comment]
Partially fixed: quotes pb is from Query object...
Now strings must be wrapped by quotes in the GUI. VQL is for advanced users and not using quotes for strings is confusing.

UPPER case for clauses is still en problem.

**Comment by ysard** [comment]
Fixed by adding ignore_case to textx.metamodel_from_str().
1 month for that. thx.

VQL editor will fail to add syntactic coloration to these keywords.

**Comment by ysard** [comment]
This can be fixed easily  with pattern option BUT we still have the problem of "all" string that is a SQL keyword; Pb related to #33 
We have to decide something about this name !

**Comment by dridk** [comment]
All selection should be rename to "variants" like the table name.

**Comment by ysard** [comment]
Ok i'm doing that

**Comment by dridk** [comment]
Values in where clause are now standard textx objects. ( String, Int, Float, Bool, Tuple ) . So it works like a regular programming language. String must be quoted, TRUE/FALSE are accepted.

**Comment by ysard** [comment]
Ok cool this part was still missing: detection of types.
