### ISSUE TITLE
Ambiguous column names

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#69]
When a column in "annotations" has the same name as another column un "variants", we have the following error:
sqlite3.OperationalError: ambiguous column name: af

Reproductibility:
Open a vcf file, and select "af" column in variants or annotations.

Solutions:
- We could take care of the names of the columns in the database.
- We could ignore this field in annotations/variants.
- We could build SELECT queries by explicitly writing the source name of the field questioned:
i.e:
SELECT ... variants.af ... FROM variants ... LEFT JOIN annotations ON ...

**Comment by dridk** [comment]
We should ignore duplicate fields. Because they are probably the same.  it's not really important and we can skip it.
