### ISSUE TITLE
About annotations, selections and variants retreived

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#73]
By doing systematically a LEFT JOIN on annotations and sometimes to selections, some queries can be very slow.
Aggregation functions like COUNT(*) may suffer from this (ex: query.variants_count()).

**Comment by dridk** [comment]
No solution actually ?

**Comment by ysard** [comment]
variants_count is now cached, and optimized if some parts of the query are fixed.
But when joints to samples are made it is time consuming and i can't do anything for the moment.
It takes 2,4second to count 1,5 million of variants resulting of a joint between 1 sample and 4millions of variants.
Also, group by, and annotations are added only if it is mandatory to satisfy the query.

**Comment by ysard** [comment]
I'm closing this. Nothing to do more here.
