### ISSUE TITLE
Inefficient set queries on selections

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#74]
- [x] Creation of selections from a set operation between 2 is inefficient: we should depend on variants unique ids for that instead of (chr, pos).

- [x] Thus. sets involving "all" default selections fail

I will try to fix that... But, why create_selection_from_sql() depends on (chr, pos) or (chr,pos,ref,alt) ?

**Comment by dridk** [comment]
See --mode from http://varianttools.sourceforge.net/Vtools/Compare

I guess using id is similar than (chr, pos,ref,alt) . Because the tuple is unique.
We can avoid (chr, pos) for now. It can be a feature for later.

**Comment by ysard** [comment]
Yes indeed, id is similar to the primary key of `variants`.
But currently, when a selection is created, the mapping is on (chr, pos);
We don't see this behavior because our examples files have unique couples of (chr, pos)...

An idea to signal this behavior to the user and let him select the desired behavior?

**Comment by dridk** [comment]
We can set a context parameter in VQL. 

SET mode=site
CREATE a = b-c

From the UI, a button somewhere to switch between type.

**Comment by ysard** [comment]
I'm not sure of the usefullness of the search mode (replacing the old 'by' arg) to search variants; In any case compare variants on some attrs is not what set operations between selections are supposed to do. Maybe its a further feature to search variants/site/genotype in the variants table according to the current selection.
We should discuss about this irl.

Cf 38acd623a17fc723bb75b2ade503f37c95010d2f

Here is an example:
- Add a variant with same chr, pos as the 11th in the db:
`INSERT into variants (chr, pos, ref, alt) values (11, 920000, 'G', 'Y')`

- Make a 1st selection (1) from the GUI: with the following VQL statement:
SELECT chr,pos,ref,alt FROM variants

- Make a 2nd selection (2) from the GUI: with the following VQL statement:
SELECT chr,pos,ref,alt FROM variants WHERE ref = "G" and alt != "Y"
(4 elements:)

| id | chr | pos | ref | alt |
| -- | -- | -- | -- | -- |
| 1 | 11 | 10000 | G | T |
| 2 | 11 | 120000 | G | T |
| 5 | 11 | 124000 | G | A |
| 11 | 11 | 920000 | G | T |

If you do an intersection between (1) and (2) with the old method SQL queries are something like that:

```
SELECT chr,pos FROM variants INNER JOIN (SELECT variant_id FROM selection_has_variant sv WHERE sv.selection_id = 2) ON variant_id = id
intersect
SELECT chr,pos FROM variants INNER JOIN (SELECT variant_id FROM selection_has_variant sv WHERE sv.selection_id = 3) ON variant_id = id
```

| chr | pos |
| -- | -- |
| 11 | 10000 |
| 11 | 120000 |
| 11 | 124000 |
| 11 | 920000 |

=> 4 criteria to search variants in the database via inner join to the 'variants' table.

The final variants retrieved will be:

| id | chr | pos | ref | alt |
| -- | -- | -- | -- | -- |
| 1 | 11 | 10000 | G | T |
| 2 | 11 | 120000 | G | T |
| 5 | 11 | 124000 | G | A |
| 11 | 11 | 920000 | G | T |
| 12 | 11 | 920000 | G | Y |

=> 5 variants instead of 4.

A feature that allows to search variants in the database according to the selected selection is ok with that behavior. Set interactions between pre-selected variants doesn't following this behavior.

concretely it can be proposed only in an additional menu via an interaction vs the default selection "variants".

**Comment by ysard** [comment]
This is fixed now, i keep the issue open just for the last proposition: 
- Add a way to do extra operations on the variant table only.
