### ISSUE TITLE
ViewQueryWidget: Cannonical transcripts

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#76]
The list of variants is very confusing when no annotation column is selected:
User may ask why he can scroll down the groups without anything that allows to distinguish elements in them.

Solution:
- [ ] Force almost 1 column in annotations to be checked
=> not fun because it forces to do sql join everytime to count variants.
- [x] Disable grouping and annotations querying when no annotation column is selected.
=> better

Also when a column in annotations is selected, a scroll down to the groups is possible, but:
- Redondance of the parent is very confusing
- The parent possess column data of one of its child (randomly selected)
- The childs display very redondant information like chr, pos, ref, alt

Such a presentation is much more appreciated:
![image](https://user-images.githubusercontent.com/14988285/57717422-896a2280-767b-11e9-97aa-92ee5af46757.png)

So:
- [x] mask confusing, not accurate and useless data on parents
- [x] mask redundant data on childs (less urgent)

This the last big improvement to do on the GUI before implementing more features...

**Comment by dridk** [comment]
You mean hide columns (chr,pos,ref,alt ) only ? Humm..
To avoid confusing , we may change color ? Use a background color for children ? 

### Idea... 
In sens, those line are not children but duplicate. So, a tree view may be a wrong choice.
What about using a simple ListView ? By double clicking on the line, you add duplicate below the first one ? 
From the end user, it's not really different.. But from the developer, it can avoid using the Tree model which is really difficult to understand.

![image](https://user-images.githubusercontent.com/1911063/57720265-c76a4500-7681-11e9-8c7b-87ac5a14dbc7.png)

**Comment by ysard** [comment]
Ok je reformule pour les colonnes:
Bah déjà si aucune colonne permettant de distinguer les variants n'est cochée, il ne faudrait pas pouvoir dérouler le variant parent (faire comme s'il n'y avait pas plusieurs annotations pour le variant).
=> ça c'est facile suffit d'enlever la jointure sur annotations (get_joints() fait ça avec do_not_add_default_things=True))

Le plus important serait de ne pas afficher les colonnes permettant de distinguer les enfants au niveau des parents => l'info est fausse car c'est une donnée prise arbitrairement parmi toutes les données des enfants.

Après que l'information redondante soit affichée ou non est moins grave/urgent. J'étais parti pour la traiter à la volée en la remplaçant par des chaines vides sur chr,pos,ref,alt. ça marche mais le premier variant de la liste étant le variant parent, lui n'est pas traité...
donc ça donne la première ligne des enfants redondante par rapport au parent, et le reste des enfants comme attendu.

**Comment by dridk** [comment]
Je pense que le group by devrait être une option de la vue au même titre que LIMIT et OFFSET.
Ca serait ptetre plus facile comme ca ! A voir .. !

**Comment by ysard** [comment]
à implémenter oui en attendant ça risque d'être le bazar sur l'affichage...
- Nécessité de dupliquer les variants dans les blocs déroulants pour cette raison + pour la multiplicité des annotations pour chaque variants.
- Masquer automatiquement les champs choisis arbitrairement; mais là on en revient à cette issue.

**Comment by ysard** [comment]
Here is what i'm purposing in d14c120

![image](https://user-images.githubusercontent.com/14988285/57864956-0bce2000-77fd-11e9-92c1-f30fc1b9140d.png)

**Comment by dridk** [comment]
I disagree with this view. You have a lot empty space and you break the symmetry . 
This is my suggestion : 

- [ ] Row should be grouped by and only by (chr,pos, ref,alt) if annotation is selected.
- [x] Expand button should be displayed only if annotation is selected 
- [ ] The cannonical transcript must be displayed as default. ( we don't have this information yet) 
- [ ] When expanding row, we must display only the missing row. Don't display the base row again

This is not a problem to have duplicate rows when variant is expand. 
To be more readable, we must set the same row background that the parent row. ( gray or white )

**Comment by dridk** [comment]
je me l'assigne !

**Comment by ysard** [comment]
Ok; reste à identifier le transcrit canonique... Les parsers sont faits, la bdd aussi, ne me dis pas qu'il y a des infos non présentes dans les fichiers de tests :D
Sinon oui ça brise la symétrie mais les infos redondantes n'aident pas à identifier clairement les points qui changent dans la masse de données.
Sinon dans la colonne genotype du variant canonique il pourrait y avoir la liste résumée des génotypes des transcrits...
Tu peux reprendre ma branche ou je fais une PR mais il faudra virer les commits en question, désolé, je n'ai pas fait de branche dédiée à cette implémentation :/

**Comment by dridk** [comment]
En fonction du genome ( hg19 dans le wizard) faudra charger refseq ( liste des transcript du genome) . Avec un peu de chance, la premiere ligne des Annotations dans le vcf est le cannonique

**Comment by ysard** [comment]
Some links:

$Canonical transcripts 
http://snpeff.sourceforge.net/SnpEff_manual.html#cmdline

Q: Why do I see so many lines of output for each variant in my input?
https://www.ensembl.org/info/docs/tools/vep/vep_faq.html


> the canonical transcript for a gene is set according to the following hierarchy: 1. Longest CCDS translation with no stop codons. 2. If no (1), choose the longest Ensembl/Havana merged translation with no stop codons. 3. If no (2), choose the longest translation with no stop codons. 4. If no translation, choose the longest non-protein-coding transcript.

http://www.ensembl.org/Help/Glossary?id=346

**Comment by dridk** [comment]
There is an option "grouped" now .
