### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#82]
Deleted because dependencies are in setup.cfg.
It avoids to maintain 2 lists of requirements.

`pip install -e .[dev]` is the only way to locally install properly the project now.

**Comment by dridk** [comment]
Ok, I removed it from travis.

**Comment by Aluriak** [comment]
To install requirements, add this in Makefile:

    install_deps:
	    python -c "import configparser; c = configparser.ConfigParser(); c.read('setup.cfg'); print(c['options']['install_requires'])" | xargs pip install -U

**Comment by ysard** [comment]
T'as pas plus complexe comme commande ? ><

Alors oui je suis d'accord que comme ça on arrive à installer les pré-requis séparément du programme principal.
Mais dans le cas présent (et en général?) le prog principal est installé juste après donc `pip install -e .[dev]` est plus rapide. C'est l'équivalent de `python setup.py develop` mais avec la possibilité de sélectionner les extras à installer.

Sinon il y a des requis dédiés au dev (et donc aux tests); ils sont dans la section ['options']['extras_require'].
La directive  install_deps est néanmoins conservée et à jour dans le Makefile.

**Comment by Aluriak** [comment]
Excuse moi d'avoir proposé une solution.

Perso, je préfère une recipe un poil complexe (et encore, c'est une lecture de fichier de config et du xargs) qui fait exactement le minimum demandé, que pip install sur fichiers locaux qui fait potentiellement des side-effect.
Par exemple, installer le package. Chose que tu veux pas forcément faire quand tu initialise un nouveau virtualenv pour tester les fichiers locaux.
Et ça implique aussi que ton packaging est valide.

**Comment by ysard** [comment]
En virtualenv local admettons c'est pour ça que la directive est encore présente.
Le pip install est de toute façon nécessaire ensuite pour exécuter le projet.

Tester la validité du packaging et donc l'installation est aussi le but de l'intégration continue.
Oui il y a des effets secondaires dans cette installation simulée mais de toute façon le vrai packaging ne peut être testé que sur un tar.gz ou depuis Pypi. Ce qui n'est pas fait ici.
