### ISSUE TITLE
cannot deploy on pypi 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#83]
After typing "make fullrelease", I get the following error. 

Response status code: 400
Reason: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
There were errors or warnings.
ERROR: Package upload has failed.
NoneType: None

**Comment by dridk** [comment]
I have no clue how to resolve it ...

**Comment by dridk** [comment]
Seems to be resolved and published on pypi

**Comment by Aluriak** [comment]
Fixed properly with 650a7157153d
