### ISSUE TITLE
unicode error on windows

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#84]
Application crash on windows during importing vcf.gz file. 
Because this function https://github.com/labsquare/cutevariant/blob/master/cutevariant/core/readerfactory.py#L38 try to read a vcf.gz as a standard text file, not a gz file

**Comment by ysard** [comment]
You should specify in a commentary why 'rb' is tested for vcf.gz. Nobody will remember that trick in a few months.

We should always specify the encoding when we open a file:
`open("fichier.txt", "r", encoding='encoding')`

Cf http://sametmax.com/lencoding-en-python-une-bonne-fois-pour-toute/
