### ISSUE TITLE
Customize cells color view with delegate

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#95]
It would be greate to allow user to create their own view with conditional color . 
For example, display color cells depending condition.
The [columnar ](https://pypi.org/project/Columnar/) package do something similar.
Here is an example which returns colors :

```
patterns["AF"] = lambda x : "green" if x < 1 else "red" 
patterns["POS"] = lambda x : "green" if x < 1 else "red" 
patterns["REF"] = lambda x : "green" if x < 1 else "red" 
```
But it may be better to return a pen color and a brush color : 

```
patterns["AF"] = lambda x : ("green" ,"transparent") if x < 1 else ("red","white") 
```

What about using regexp  ?

What do you think ? @Aluriak @ysard

**Comment by dridk** [comment]
For performance reason.... I will not use delegate for this purpose because it requires to compute each time the line is displayed. I will return color from the model using Qt.TextColorRole etc ....

**Comment by Aluriak** [comment]
You can still assign roles after user gave the rules.
You want a mini language ?

    if AF < 1:
        AF is green transparent
    else:
        AF is red white
